project_id = "ynoiwioypxpurwdbjvyt"

[functions.car-advisor]
verify_jwt = true

[functions.car-finder]
verify_jwt = false

[functions.car-recommendations]
verify_jwt = false

[functions.submit-lead]
verify_jwt = true
