import { useState, useEffect, useCallback, useRef } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toast } from "sonner";
import ReactMarkdown from "react-markdown";
import {
  Sparkles, CheckCircle2, Clock, AlertTriangle, Zap,
  Send, RefreshCcw, Target, TrendingUp, Brain, Rocket,
  ThumbsUp, X, MessageCircle
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { format } from "date-fns";

const CHAT_URL = `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/ai-cofounder`;

function useBriefingStream() {
  const [content, setContent] = useState("");
  const [isStreaming, setIsStreaming] = useState(false);

  const startStream = useCallback(async (action: string, extras: any = {}) => {
    setContent("");
    setIsStreaming(true);

    try {
      const resp = await fetch(CHAT_URL, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY}`,
        },
        body: JSON.stringify({ action, ...extras }),
      });

      if (!resp.ok || !resp.body) {
        const err = await resp.json().catch(() => ({}));
        throw new Error(err.error || `Error ${resp.status}`);
      }

      const reader = resp.body.getReader();
      const decoder = new TextDecoder();
      let buffer = "";
      let accumulated = "";

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });

        let newlineIdx: number;
        while ((newlineIdx = buffer.indexOf("\n")) !== -1) {
          let line = buffer.slice(0, newlineIdx);
          buffer = buffer.slice(newlineIdx + 1);
          if (line.endsWith("\r")) line = line.slice(0, -1);
          if (!line.startsWith("data: ")) continue;
          const jsonStr = line.slice(6).trim();
          if (jsonStr === "[DONE]") break;
          try {
            const parsed = JSON.parse(jsonStr);
            const token = parsed.choices?.[0]?.delta?.content;
            if (token) {
              accumulated += token;
              setContent(accumulated);
            }
          } catch { /* partial */ }
        }
      }
    } catch (e: any) {
      toast.error(e.message || "Failed to get AI briefing");
    } finally {
      setIsStreaming(false);
    }
  }, []);

  return { content, isStreaming, startStream };
}

export default function AICofounderDashboard() {
  const qc = useQueryClient();
  const [activeTab, setActiveTab] = useState("briefing");
  const [question, setQuestion] = useState("");
  const briefing = useBriefingStream();
  const insight = useBriefingStream();

  // Fetch today's AI tasks
  const today = format(new Date(), "yyyy-MM-dd");
  const { data: tasks = [], isLoading: tasksLoading } = useQuery({
    queryKey: ["cofounder-tasks", today],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("ai_cofounder_tasks")
        .select("*")
        .eq("due_date", today)
        .order("priority", { ascending: true })
        .order("created_at", { ascending: false });
      if (error) throw error;
      return data || [];
    },
  });

  // Generate tasks via AI
  const generateTasks = useMutation({
    mutationFn: async () => {
      const resp = await fetch(CHAT_URL, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY}`,
        },
        body: JSON.stringify({ action: "suggest_tasks", user_name: "Boss", user_role: "founder" }),
      });
      if (!resp.ok) throw new Error("Failed to generate tasks");
      return resp.json();
    },
    onSuccess: (data) => {
      qc.invalidateQueries({ queryKey: ["cofounder-tasks"] });
      toast.success(`${data.tasks?.length || 0} tasks generated by AI Co-Founder!`);
    },
    onError: (e: any) => toast.error(e.message),
  });

  // Approve/complete/dismiss task
  const updateTask = useMutation({
    mutationFn: async ({ id, action }: { id: string; action: "approve" | "complete" | "dismiss" }) => {
      const update: any = {};
      if (action === "approve") update.status = "approved";
      if (action === "approve") update.approved_at = new Date().toISOString();
      if (action === "complete") update.status = "completed";
      if (action === "complete") update.completed_at = new Date().toISOString();
      if (action === "dismiss") update.status = "dismissed";
      if (action === "dismiss") update.dismissed_at = new Date().toISOString();
      const { error } = await supabase.from("ai_cofounder_tasks").update(update).eq("id", id);
      if (error) throw error;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["cofounder-tasks"] });
      toast.success("Task updated");
    },
  });

  // Auto-load briefing on mount
  useEffect(() => {
    if (activeTab === "briefing" && !briefing.content && !briefing.isStreaming) {
      briefing.startStream("daily_briefing", { user_name: "Boss", user_role: "founder" });
    }
  }, [activeTab]);

  const priorityConfig: Record<string, { color: string; icon: any }> = {
    urgent: { color: "bg-red-500/10 text-red-600 border-red-200", icon: AlertTriangle },
    high: { color: "bg-orange-500/10 text-orange-600 border-orange-200", icon: Zap },
    medium: { color: "bg-blue-500/10 text-blue-600 border-blue-200", icon: Clock },
    low: { color: "bg-green-500/10 text-green-600 border-green-200", icon: CheckCircle2 },
  };

  const taskStats = {
    total: tasks.length,
    pending: tasks.filter((t: any) => t.status === "pending").length,
    approved: tasks.filter((t: any) => t.status === "approved").length,
    completed: tasks.filter((t: any) => t.status === "completed").length,
    urgent: tasks.filter((t: any) => t.priority === "urgent").length,
  };

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="p-2.5 rounded-xl bg-gradient-to-br from-violet-500 to-purple-600 text-white shadow-lg">
            <Brain className="h-6 w-6" />
          </div>
          <div>
            <h2 className="text-xl font-bold flex items-center gap-2">
              AI Co-Founder <Sparkles className="h-5 w-5 text-amber-500" />
            </h2>
            <p className="text-xs text-muted-foreground">Your intelligent business partner — always on, always pushing growth</p>
          </div>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" className="gap-1" onClick={() => briefing.startStream("daily_briefing", { user_name: "Boss", user_role: "founder" })}>
            <RefreshCcw className={`h-3.5 w-3.5 ${briefing.isStreaming ? "animate-spin" : ""}`} /> Refresh Briefing
          </Button>
          <Button size="sm" className="gap-1 bg-gradient-to-r from-violet-600 to-purple-600" onClick={() => generateTasks.mutate()} disabled={generateTasks.isPending}>
            <Rocket className={`h-3.5 w-3.5 ${generateTasks.isPending ? "animate-bounce" : ""}`} />
            {generateTasks.isPending ? "Generating..." : "Generate Today's Tasks"}
          </Button>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-5 gap-3">
        {[
          { label: "Total Tasks", value: taskStats.total, icon: Target, gradient: "from-blue-500 to-indigo-600" },
          { label: "Pending", value: taskStats.pending, icon: Clock, gradient: "from-amber-500 to-orange-600" },
          { label: "Approved", value: taskStats.approved, icon: ThumbsUp, gradient: "from-green-500 to-emerald-600" },
          { label: "Completed", value: taskStats.completed, icon: CheckCircle2, gradient: "from-teal-500 to-cyan-600" },
          { label: "Urgent", value: taskStats.urgent, icon: AlertTriangle, gradient: taskStats.urgent > 0 ? "from-red-500 to-rose-600" : "from-gray-400 to-gray-500" },
        ].map((s, i) => (
          <motion.div key={s.label} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.05 }}>
            <Card className="overflow-hidden">
              <div className={`h-1 bg-gradient-to-r ${s.gradient}`} />
              <CardContent className="pt-3 pb-2.5 flex items-center gap-3">
                <div className={`p-2 rounded-lg bg-gradient-to-br ${s.gradient} text-white`}><s.icon className="h-4 w-4" /></div>
                <div>
                  <p className="text-lg font-bold leading-tight">{s.value}</p>
                  <p className="text-[10px] text-muted-foreground">{s.label}</p>
                </div>
              </CardContent>
            </Card>
          </motion.div>
        ))}
      </div>

      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList className="grid grid-cols-3 w-full max-w-md">
          <TabsTrigger value="briefing" className="gap-1"><Sparkles className="h-3.5 w-3.5" /> Daily Briefing</TabsTrigger>
          <TabsTrigger value="tasks" className="gap-1 relative">
            <Target className="h-3.5 w-3.5" /> Tasks
            {taskStats.pending > 0 && <span className="absolute -top-1 -right-1 bg-red-500 text-white text-[8px] rounded-full w-4 h-4 flex items-center justify-center">{taskStats.pending}</span>}
          </TabsTrigger>
          <TabsTrigger value="ask" className="gap-1"><MessageCircle className="h-3.5 w-3.5" /> Ask Co-Founder</TabsTrigger>
        </TabsList>

        {/* Daily Briefing */}
        <TabsContent value="briefing" className="mt-4">
          <Card className="border-violet-200 dark:border-violet-800">
            <CardHeader className="pb-2">
              <CardTitle className="text-sm flex items-center gap-2">
                <Sparkles className="h-4 w-4 text-violet-500" />
                {format(new Date(), "EEEE, dd MMMM yyyy")} — Daily Briefing
                {briefing.isStreaming && <Badge variant="outline" className="text-[10px] animate-pulse">🔴 Live</Badge>}
              </CardTitle>
            </CardHeader>
            <CardContent>
              {briefing.content ? (
                <ScrollArea className="max-h-[500px]">
                  <div className="prose prose-sm dark:prose-invert max-w-none">
                    <ReactMarkdown>{briefing.content}</ReactMarkdown>
                  </div>
                </ScrollArea>
              ) : briefing.isStreaming ? (
                <div className="flex items-center gap-3 py-8">
                  <div className="animate-spin rounded-full h-8 w-8 border-2 border-violet-500 border-t-transparent" />
                  <div>
                    <p className="font-medium">AI Co-Founder is analyzing your business...</p>
                    <p className="text-xs text-muted-foreground">Scanning leads, renewals, orders, follow-ups...</p>
                  </div>
                </div>
              ) : (
                <div className="text-center py-8 text-muted-foreground">
                  <Brain className="h-12 w-12 mx-auto mb-3 opacity-20" />
                  <p>Click "Refresh Briefing" to get today's AI briefing</p>
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* Tasks */}
        <TabsContent value="tasks" className="mt-4 space-y-3">
          {tasks.length === 0 && !tasksLoading ? (
            <Card>
              <CardContent className="py-8 text-center text-muted-foreground">
                <Rocket className="h-12 w-12 mx-auto mb-3 opacity-20" />
                <p className="font-medium">No tasks for today yet</p>
                <p className="text-sm mt-1">Click "Generate Today's Tasks" to let AI create your action plan</p>
              </CardContent>
            </Card>
          ) : (
            <AnimatePresence>
              {tasks.map((task: any, i: number) => {
                const pc = priorityConfig[task.priority] || priorityConfig.medium;
                const PIcon = pc.icon;
                return (
                  <motion.div key={task.id} initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0 }} transition={{ delay: i * 0.03 }}>
                    <Card className={`border-l-4 ${task.priority === "urgent" ? "border-l-red-500" : task.priority === "high" ? "border-l-orange-500" : task.priority === "medium" ? "border-l-blue-500" : "border-l-green-500"} ${task.status === "completed" ? "opacity-60" : ""}`}>
                      <CardContent className="py-3">
                        <div className="flex items-start justify-between gap-3">
                          <div className="flex items-start gap-3 flex-1">
                            <div className={`p-2 rounded-lg mt-0.5 ${pc.color}`}><PIcon className="h-4 w-4" /></div>
                            <div className="flex-1 min-w-0">
                              <div className="flex items-center gap-2 flex-wrap">
                                <p className={`font-medium text-sm ${task.status === "completed" ? "line-through" : ""}`}>{task.title}</p>
                                <Badge variant="outline" className={`text-[9px] ${pc.color}`}>{task.priority}</Badge>
                                <Badge variant="secondary" className="text-[9px]">{task.task_type?.replace(/_/g, " ")}</Badge>
                                {task.vertical && <Badge variant="outline" className="text-[9px]">{task.vertical}</Badge>}
                                <Badge variant={task.status === "completed" ? "default" : task.status === "approved" ? "default" : "secondary"} className="text-[9px]">
                                  {task.status}
                                </Badge>
                              </div>
                              {task.description && <p className="text-xs text-muted-foreground mt-1">{task.description}</p>}
                              {task.ai_suggestion && (
                                <p className="text-xs text-violet-600 dark:text-violet-400 mt-1 flex items-center gap-1">
                                  <Sparkles className="h-3 w-3" /> {task.ai_suggestion}
                                </p>
                              )}
                              {task.team_member_name && (
                                <p className="text-[10px] text-muted-foreground mt-1">👤 Assigned: {task.team_member_name}</p>
                              )}
                            </div>
                          </div>
                          {task.status === "pending" && (
                            <div className="flex gap-1 flex-shrink-0">
                              <Button size="sm" variant="outline" className="h-7 gap-1 text-green-600 hover:bg-green-50" onClick={() => updateTask.mutate({ id: task.id, action: "approve" })}>
                                <ThumbsUp className="h-3 w-3" /> Approve
                              </Button>
                              <Button size="sm" variant="ghost" className="h-7 text-muted-foreground" onClick={() => updateTask.mutate({ id: task.id, action: "dismiss" })}>
                                <X className="h-3 w-3" />
                              </Button>
                            </div>
                          )}
                          {task.status === "approved" && (
                            <Button size="sm" variant="outline" className="h-7 gap-1" onClick={() => updateTask.mutate({ id: task.id, action: "complete" })}>
                              <CheckCircle2 className="h-3 w-3" /> Done
                            </Button>
                          )}
                        </div>
                      </CardContent>
                    </Card>
                  </motion.div>
                );
              })}
            </AnimatePresence>
          )}
        </TabsContent>

        {/* Ask Co-Founder */}
        <TabsContent value="ask" className="mt-4">
          <Card className="border-violet-200 dark:border-violet-800">
            <CardHeader className="pb-2">
              <CardTitle className="text-sm flex items-center gap-2">
                <Brain className="h-4 w-4 text-violet-500" /> Ask Your AI Co-Founder
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex gap-2">
                <Input
                  placeholder="Ask anything... e.g. 'How to boost insurance renewals?' or 'Which leads should I call first?'"
                  value={question}
                  onChange={e => setQuestion(e.target.value)}
                  onKeyDown={e => { if (e.key === "Enter" && question.trim()) { insight.startStream("quick_insight", { question, user_name: "Boss", user_role: "founder" }); } }}
                  className="flex-1"
                />
                <Button className="gap-1 bg-gradient-to-r from-violet-600 to-purple-600" onClick={() => insight.startStream("quick_insight", { question, user_name: "Boss", user_role: "founder" })} disabled={!question.trim() || insight.isStreaming}>
                  <Send className="h-4 w-4" />
                </Button>
              </div>

              <div className="flex flex-wrap gap-2">
                {[
                  "How to hit ₹10L revenue this week?",
                  "Which leads are most likely to convert?",
                  "What cross-sell opportunities exist?",
                  "Team performance review",
                  "Overdue follow-ups action plan",
                ].map(q => (
                  <Button key={q} variant="outline" size="sm" className="text-xs h-7" onClick={() => { setQuestion(q); insight.startStream("quick_insight", { question: q, user_name: "Boss", user_role: "founder" }); }}>
                    {q}
                  </Button>
                ))}
              </div>

              {insight.content ? (
                <ScrollArea className="max-h-[400px]">
                  <div className="prose prose-sm dark:prose-invert max-w-none p-4 bg-muted/30 rounded-xl">
                    <ReactMarkdown>{insight.content}</ReactMarkdown>
                  </div>
                </ScrollArea>
              ) : insight.isStreaming ? (
                <div className="flex items-center gap-3 py-6">
                  <div className="animate-spin rounded-full h-6 w-6 border-2 border-violet-500 border-t-transparent" />
                  <p className="text-sm text-muted-foreground">Thinking like a founder...</p>
                </div>
              ) : null}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
