import { useState, useRef, useEffect, useCallback } from "react";
import { useParams } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { useAgreementByToken, useAddAgreementHistory } from "@/hooks/useRentalAgreements";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Skeleton } from "@/components/ui/skeleton";
import { SectionErrorBoundary } from "@/components/SectionErrorBoundary";
import { toast } from "sonner";
import { format } from "date-fns";
import {
  CheckCircle2, FileText, Pen, Type, Upload, ShieldCheck,
  Car, Phone, Calendar, MapPin, CreditCard, AlertTriangle, Download,
} from "lucide-react";
import jsPDF from "jspdf";

// ─── helpers ───────────────────────────────────────────────────────
async function getClientIP(): Promise<string> {
  try {
    const res = await fetch("https://api.ipify.org?format=json");
    const data = await res.json();
    return data.ip || "unknown";
  } catch { return "unknown"; }
}

function getDeviceInfo(): string {
  try { return navigator.userAgent; } catch { return "unknown"; }
}

function generateSignedPDF(agreement: any, signatureName: string, signatureType: string, signatureData: string) {
  const doc = new jsPDF();
  const w = doc.internal.pageSize.getWidth();
  
  // Header
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("GrabYourCar", w / 2, 20, { align: "center" });
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Self-Drive Rental Agreement", w / 2, 27, { align: "center" });
  doc.setFontSize(8);
  doc.text(agreement.agreement_number || "", w / 2, 32, { align: "center" });
  
  doc.line(15, 36, w - 15, 36);
  
  // Details
  let y = 44;
  doc.setFontSize(10);
  const details = [
    ["Customer", agreement.customer_name],
    ["Phone", agreement.customer_phone],
    ["Vehicle", `${agreement.vehicle_name || "N/A"} ${agreement.vehicle_number ? `(${agreement.vehicle_number})` : ""}`],
    ["Pickup Date", agreement.pickup_date || "N/A"],
    ["Dropoff Date", agreement.dropoff_date || "N/A"],
    ["Pickup Location", agreement.pickup_location || "N/A"],
    ["Dropoff Location", agreement.dropoff_location || "N/A"],
    ["Rental Amount", `Rs. ${(agreement.rental_amount || 0).toLocaleString("en-IN")}`],
    ["Security Deposit", `Rs. ${(agreement.security_deposit || 0).toLocaleString("en-IN")}`],
  ];
  
  details.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, 18, y);
    doc.setFont("helvetica", "normal");
    doc.text(String(value), 65, y);
    y += 7;
  });
  
  // Terms (plain text stripped from HTML)
  y += 5;
  doc.line(15, y, w - 15, y);
  y += 8;
  doc.setFont("helvetica", "bold");
  doc.text("Terms & Conditions", 18, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  const plainTerms = agreement.terms_html.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim();
  const lines = doc.splitTextToSize(plainTerms, w - 36);
  lines.forEach((line: string) => {
    if (y > 260) { doc.addPage(); y = 20; }
    doc.text(line, 18, y);
    y += 4.5;
  });
  
  // Signature section
  if (y > 230) { doc.addPage(); y = 20; }
  y += 10;
  doc.line(15, y, w - 15, y);
  y += 8;
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Digital Signature", 18, y);
  y += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Signed by: ${signatureName}`, 18, y);
  y += 6;
  doc.text(`Method: ${signatureType === "draw" ? "Hand-drawn signature" : "Typed name"}`, 18, y);
  y += 6;
  doc.text(`Date: ${format(new Date(), "PPpp")}`, 18, y);
  y += 6;
  
  if (signatureType === "draw" && signatureData) {
    try { doc.addImage(signatureData, "PNG", 18, y, 80, 25); y += 30; } catch { /* skip */ }
  } else if (signatureType === "type") {
    y += 4;
    doc.setFontSize(20);
    doc.setFont("times", "italic");
    doc.text(signatureData, 18, y);
    y += 12;
  }
  
  // Footer
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.text("This is a legally binding digital agreement. Generated by GrabYourCar.", w / 2, 285, { align: "center" });
  
  return doc;
}

// ─── Loading Skeleton ──────────────────────────────────────────────
function AgreementSkeleton() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-emerald-50 via-white to-cyan-50 py-6 px-4">
      <div className="max-w-2xl mx-auto space-y-6">
        <div className="text-center space-y-3">
          <Skeleton className="h-10 w-48 mx-auto rounded-full" />
          <Skeleton className="h-6 w-64 mx-auto" />
          <Skeleton className="h-4 w-32 mx-auto" />
        </div>
        <Skeleton className="h-48 w-full rounded-lg" />
        <Skeleton className="h-64 w-full rounded-lg" />
        <Skeleton className="h-32 w-full rounded-lg" />
      </div>
    </div>
  );
}

// ─── Error State ───────────────────────────────────────────────────
function AgreementError({ message }: { message?: string }) {
  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-red-50 to-orange-50 dark:from-gray-950 dark:to-gray-900 px-4">
      <Card className="max-w-md w-full">
        <CardContent className="py-8 text-center">
          <AlertTriangle className="h-12 w-12 mx-auto mb-4 text-destructive" />
          <h2 className="text-lg font-bold">Agreement Not Found</h2>
          <p className="text-sm text-muted-foreground mt-2">
            {message || "This link may be expired, invalid, or the agreement has been removed."}
          </p>
          <p className="text-xs text-muted-foreground mt-4">
            If you believe this is an error, please contact GrabYourCar support.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}

// ─── Main Component ────────────────────────────────────────────────
export default function AgreementSignPage() {
  const { token } = useParams<{ token: string }>();
  const { data: agreement, isLoading, error, refetch } = useAgreementByToken(token || null);
  const addHistory = useAddAgreementHistory();

  const [signMode, setSignMode] = useState<"type" | "draw" | null>(null);
  const [typedName, setTypedName] = useState("");
  const [agreed, setAgreed] = useState(false);
  const [signing, setSigning] = useState(false);
  const [signed, setSigned] = useState(false);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [isDrawing, setIsDrawing] = useState(false);

  // KYC
  const [kycStep, setKycStep] = useState(false);
  const [kycUploads, setKycUploads] = useState<Record<string, { front?: File; back?: File; number: string }>>({
    aadhaar: { number: "" }, driving_license: { number: "" },
    pan_card: { number: "" }, address_proof: { number: "" },
  });
  const [uploadingKyc, setUploadingKyc] = useState(false);
  const [kycDone, setKycDone] = useState(false);

  // Mark as viewed
  useEffect(() => {
    if (agreement && !agreement.client_viewed_at && agreement.status === "sent") {
      supabase.from("rental_agreements")
        .update({ client_viewed_at: new Date().toISOString(), status: "viewed" } as any)
        .eq("id", agreement.id)
        .then(() => {
          addHistory.mutate({
            agreement_id: agreement.id,
            action: "viewed_by_client",
            action_by: agreement.customer_name,
          });
        });
    }
  }, [agreement?.id]); // eslint-disable-line

  // Canvas
  useEffect(() => {
    if (signMode === "draw" && canvasRef.current) {
      const ctx = canvasRef.current.getContext("2d");
      if (ctx) { ctx.lineWidth = 2; ctx.strokeStyle = "#1a1a2e"; ctx.lineCap = "round"; }
    }
  }, [signMode]);

  const getPos = useCallback((e: React.MouseEvent | React.TouchEvent) => {
    const canvas = canvasRef.current;
    if (!canvas) return { x: 0, y: 0 };
    const rect = canvas.getBoundingClientRect();
    const scaleX = canvas.width / rect.width;
    const scaleY = canvas.height / rect.height;
    if ("touches" in e) {
      return { x: (e.touches[0].clientX - rect.left) * scaleX, y: (e.touches[0].clientY - rect.top) * scaleY };
    }
    return { x: (e.clientX - rect.left) * scaleX, y: (e.clientY - rect.top) * scaleY };
  }, []);

  const startDraw = useCallback((e: React.MouseEvent | React.TouchEvent) => {
    e.preventDefault();
    setIsDrawing(true);
    const ctx = canvasRef.current?.getContext("2d");
    const { x, y } = getPos(e);
    ctx?.beginPath();
    ctx?.moveTo(x, y);
  }, [getPos]);

  const draw = useCallback((e: React.MouseEvent | React.TouchEvent) => {
    if (!isDrawing) return;
    e.preventDefault();
    const ctx = canvasRef.current?.getContext("2d");
    const { x, y } = getPos(e);
    ctx?.lineTo(x, y);
    ctx?.stroke();
  }, [isDrawing, getPos]);

  const stopDraw = useCallback(() => setIsDrawing(false), []);

  const clearCanvas = useCallback(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    canvas.getContext("2d")?.clearRect(0, 0, canvas.width, canvas.height);
  }, []);

  // Sign
  const handleSign = async () => {
    if (!agreement || !agreed) return;
    let sigData = "";
    if (signMode === "type") {
      if (!typedName.trim()) { toast.error("Please type your full name"); return; }
      sigData = typedName.trim();
    } else if (signMode === "draw") {
      const canvas = canvasRef.current;
      if (!canvas) return;
      sigData = canvas.toDataURL("image/png");
    } else {
      toast.error("Please select a signature method"); return;
    }

    setSigning(true);
    try {
      const [clientIP, userAgent] = await Promise.all([getClientIP(), Promise.resolve(getDeviceInfo())]);

      await supabase.from("rental_agreements").update({
        client_signed_at: new Date().toISOString(),
        client_signature_type: signMode,
        client_signature_data: sigData,
        client_signed_name: signMode === "type" ? typedName.trim() : agreement.customer_name,
        client_ip_address: clientIP,
        client_user_agent: userAgent,
        status: "signed",
      } as any).eq("id", agreement.id);

      await addHistory.mutateAsync({
        agreement_id: agreement.id,
        action: "signed_by_client",
        action_by: agreement.customer_name,
        details: { signature_type: signMode, ip: clientIP, device: userAgent.substring(0, 100) },
      });

      setSigned(true);
      toast.success("Agreement signed successfully!");
      refetch();
    } catch (e: any) {
      toast.error("Signing failed: " + e.message);
    } finally {
      setSigning(false);
    }
  };

  // Download PDF
  const handleDownloadPDF = () => {
    if (!agreement) return;
    try {
      const doc = generateSignedPDF(
        agreement,
        agreement.client_signed_name || typedName || agreement.customer_name,
        agreement.client_signature_type || signMode || "type",
        agreement.client_signature_data || typedName || "",
      );
      doc.save(`${agreement.agreement_number || "agreement"}.pdf`);
      toast.success("PDF downloaded!");
    } catch (e: any) {
      toast.error("PDF generation failed");
    }
  };

  // KYC Upload
  const handleKYCUpload = async () => {
    if (!agreement) return;
    setUploadingKyc(true);
    try {
      for (const [docType, docData] of Object.entries(kycUploads)) {
        if (!docData.front && !docData.number) continue;
        let frontUrl = null, backUrl = null;

        if (docData.front) {
          const path = `${agreement.customer_phone}/${docType}_front_${Date.now()}`;
          const { error: upErr } = await supabase.storage.from("kyc-documents").upload(path, docData.front);
          if (!upErr) { frontUrl = supabase.storage.from("kyc-documents").getPublicUrl(path).data.publicUrl; }
        }
        if (docData.back) {
          const path = `${agreement.customer_phone}/${docType}_back_${Date.now()}`;
          const { error: upErr } = await supabase.storage.from("kyc-documents").upload(path, docData.back);
          if (!upErr) { backUrl = supabase.storage.from("kyc-documents").getPublicUrl(path).data.publicUrl; }
        }

        if (frontUrl || docData.number) {
          await supabase.from("rental_kyc_documents").insert([{
            agreement_id: agreement.id, customer_phone: agreement.customer_phone,
            customer_name: agreement.customer_name, document_type: docType,
            document_number: docData.number || null,
            document_front_url: frontUrl, document_back_url: backUrl,
            verification_status: "pending",
          }] as any);
        }
      }
      await addHistory.mutateAsync({ agreement_id: agreement.id, action: "kyc_uploaded", action_by: agreement.customer_name });
      setKycDone(true);
      toast.success("KYC documents uploaded!");
    } catch (e: any) {
      toast.error(e.message);
    } finally {
      setUploadingKyc(false);
    }
  };

  // ─── Render States ─────────────────────────────────────────────
  if (!token) return <AgreementError message="No agreement token provided in the URL." />;
  if (isLoading) return <AgreementSkeleton />;
  if (error || !agreement) return <AgreementError />;

  const alreadySigned = !!agreement.client_signed_at || signed;

  return (
    <SectionErrorBoundary sectionName="AgreementSignPage">
      <div className="min-h-screen bg-gradient-to-br from-emerald-50 via-white to-cyan-50 dark:from-gray-950 dark:to-gray-900 py-6 px-4">
        <div className="max-w-2xl mx-auto space-y-6">

          {/* Brand Header */}
          <div className="text-center">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10">
              <Car className="h-5 w-5 text-primary" />
              <span className="font-bold text-primary text-lg" style={{ fontFamily: "'Outfit', sans-serif" }}>GrabYourCar</span>
            </div>
            <h1 className="text-xl font-bold mt-3" style={{ fontFamily: "'Outfit', sans-serif" }}>Self-Drive Rental Agreement</h1>
            <div className="flex items-center justify-center gap-2 mt-1">
              <Badge variant="outline" className="text-xs">{agreement.agreement_number}</Badge>
              <Badge className={
                agreement.status === "signed" ? "bg-emerald-100 text-emerald-700" :
                agreement.status === "viewed" ? "bg-amber-100 text-amber-700" :
                "bg-blue-100 text-blue-700"
              }>{agreement.status.toUpperCase()}</Badge>
            </div>
          </div>

          {/* Agreement Details */}
          <Card className="border-primary/20 shadow-sm">
            <CardContent className="py-5 space-y-4">
              <h3 className="font-semibold text-sm flex items-center gap-2" style={{ fontFamily: "'Outfit', sans-serif" }}>
                <FileText className="h-4 w-4 text-primary" /> Booking Details
              </h3>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm">
                <DetailRow icon={Phone} label="Customer" value={agreement.customer_name} />
                <DetailRow icon={Phone} label="Phone" value={agreement.customer_phone} />
                {agreement.vehicle_name && <DetailRow icon={Car} label="Vehicle" value={`${agreement.vehicle_name} ${agreement.vehicle_number ? `(${agreement.vehicle_number})` : ""}`} />}
                {agreement.pickup_date && <DetailRow icon={Calendar} label="Pickup" value={agreement.pickup_date} />}
                {agreement.dropoff_date && <DetailRow icon={Calendar} label="Dropoff" value={agreement.dropoff_date} />}
                {agreement.pickup_location && <DetailRow icon={MapPin} label="Pickup Location" value={agreement.pickup_location} />}
                {agreement.dropoff_location && <DetailRow icon={MapPin} label="Dropoff Location" value={agreement.dropoff_location} />}
                <DetailRow icon={CreditCard} label="Rental Amount" value={`₹${(agreement.rental_amount || 0).toLocaleString("en-IN")}`} highlight />
                <DetailRow icon={CreditCard} label="Security Deposit" value={`₹${(agreement.security_deposit || 0).toLocaleString("en-IN")}`} />
              </div>
            </CardContent>
          </Card>

          {/* Terms */}
          <Card className="shadow-sm">
            <CardContent className="py-5">
              <h3 className="font-semibold text-sm mb-3 flex items-center gap-2" style={{ fontFamily: "'Outfit', sans-serif" }}>
                <FileText className="h-4 w-4 text-primary" /> Terms & Conditions
              </h3>
              <div className="prose prose-sm max-w-none text-xs leading-relaxed" style={{ fontFamily: "'Inter', sans-serif" }}
                dangerouslySetInnerHTML={{ __html: agreement.terms_html }} />
            </CardContent>
          </Card>

          {/* ─── SIGNED STATE ──────────────────────────────────── */}
          {alreadySigned ? (
            <Card className="border-emerald-300 bg-emerald-50/50 dark:bg-emerald-950/20 shadow-sm">
              <CardContent className="py-6 text-center space-y-4">
                <CheckCircle2 className="h-14 w-14 mx-auto text-emerald-500" />
                <div>
                  <h3 className="font-bold text-lg text-emerald-700 dark:text-emerald-300">Agreement Signed Successfully!</h3>
                  <p className="text-sm text-muted-foreground mt-1">
                    Signed by <strong>{agreement.client_signed_name || typedName}</strong> on{" "}
                    {agreement.client_signed_at ? format(new Date(agreement.client_signed_at), "PPpp") : "just now"}
                  </p>
                </div>

                {/* Signature display */}
                {agreement.client_signature_type === "draw" && agreement.client_signature_data && (
                  <div className="inline-block bg-white border rounded-lg p-3">
                    <img src={agreement.client_signature_data} alt="Signature" className="h-16" />
                  </div>
                )}
                {agreement.client_signature_type === "type" && agreement.client_signature_data && (
                  <div className="inline-block bg-white border rounded-lg px-6 py-3">
                    <span className="text-2xl italic font-serif text-black">{agreement.client_signature_data}</span>
                  </div>
                )}

                <div className="flex flex-col sm:flex-row gap-2 justify-center pt-2">
                  <Button variant="outline" className="gap-2" onClick={handleDownloadPDF}>
                    <Download className="h-4 w-4" /> Download Signed PDF
                  </Button>
                  {!kycStep && !kycDone && (
                    <Button className="gap-2" onClick={() => setKycStep(true)}>
                      <Upload className="h-4 w-4" /> Upload KYC Documents
                    </Button>
                  )}
                </div>
              </CardContent>
            </Card>
          ) : (
            /* ─── SIGNING FLOW ────────────────────────────────── */
            <Card className="shadow-sm border-primary/20">
              <CardContent className="py-5 space-y-5">
                <h3 className="font-semibold text-sm flex items-center gap-2" style={{ fontFamily: "'Outfit', sans-serif" }}>
                  <Pen className="h-4 w-4 text-primary" /> Review & Sign Agreement
                </h3>

                {/* Agree checkbox */}
                <div className="flex items-start gap-3 p-3 rounded-lg bg-muted/50 border">
                  <Checkbox id="agree" checked={agreed} onCheckedChange={(v) => setAgreed(v === true)} className="mt-0.5" />
                  <label htmlFor="agree" className="text-sm cursor-pointer leading-relaxed">
                    I have read, understood, and agree to all the terms and conditions of this rental agreement. I confirm all details above are correct.
                  </label>
                </div>

                {agreed && (
                  <div className="space-y-4">
                    <p className="text-xs text-muted-foreground">Choose how you'd like to sign:</p>
                    <div className="flex gap-2">
                      <Button variant={signMode === "type" ? "default" : "outline"} size="sm" className="gap-1.5 flex-1" onClick={() => setSignMode("type")}>
                        <Type className="h-3.5 w-3.5" /> Type Name
                      </Button>
                      <Button variant={signMode === "draw" ? "default" : "outline"} size="sm" className="gap-1.5 flex-1" onClick={() => setSignMode("draw")}>
                        <Pen className="h-3.5 w-3.5" /> Draw Signature
                      </Button>
                    </div>

                    {signMode === "type" && (
                      <div className="space-y-2">
                        <Label className="text-xs">Type your full legal name as signature</Label>
                        <Input value={typedName} onChange={e => setTypedName(e.target.value)} placeholder="Your full legal name" />
                        {typedName && (
                          <div className="p-4 border rounded-lg bg-white text-center">
                            <span className="text-2xl italic font-serif text-black">{typedName}</span>
                            <p className="text-[10px] text-muted-foreground mt-2">This will be your digital signature</p>
                          </div>
                        )}
                      </div>
                    )}

                    {signMode === "draw" && (
                      <div className="space-y-2">
                        <Label className="text-xs">Draw your signature in the box below</Label>
                        <canvas ref={canvasRef} width={600} height={180}
                          className="border-2 border-dashed rounded-lg w-full bg-white cursor-crosshair touch-none"
                          style={{ height: "150px" }}
                          onMouseDown={startDraw} onMouseMove={draw} onMouseUp={stopDraw} onMouseLeave={stopDraw}
                          onTouchStart={startDraw} onTouchMove={draw} onTouchEnd={stopDraw}
                        />
                        <Button variant="ghost" size="sm" onClick={clearCanvas} className="text-xs">Clear Signature</Button>
                      </div>
                    )}

                    {signMode && (
                      <div className="pt-2">
                        <Button className="w-full gap-2 h-12 text-base" onClick={handleSign} disabled={signing}>
                          <CheckCircle2 className="h-5 w-5" />
                          {signing ? "Signing Agreement..." : "Submit & Sign Agreement"}
                        </Button>
                        <p className="text-[10px] text-center text-muted-foreground mt-2">
                          By clicking above, you digitally sign this agreement. Your IP address and device info will be recorded.
                        </p>
                      </div>
                    )}
                  </div>
                )}
              </CardContent>
            </Card>
          )}

          {/* ─── KYC UPLOAD ────────────────────────────────────── */}
          {kycStep && !kycDone && (
            <Card className="shadow-sm">
              <CardContent className="py-5 space-y-4">
                <div className="flex items-center gap-2">
                  <ShieldCheck className="h-5 w-5 text-primary" />
                  <h3 className="font-semibold text-sm" style={{ fontFamily: "'Outfit', sans-serif" }}>KYC Verification</h3>
                </div>
                <p className="text-xs text-muted-foreground">Upload the following documents for identity verification. All 4 documents are required.</p>

                {(["aadhaar", "driving_license", "pan_card", "address_proof"] as const).map(docType => (
                  <div key={docType} className="border rounded-lg p-3 space-y-2">
                    <Label className="text-sm font-medium capitalize">{docType.replace(/_/g, " ")}</Label>
                    <Input placeholder={`${docType.replace(/_/g, " ")} number`}
                      value={kycUploads[docType]?.number || ""}
                      onChange={e => setKycUploads(prev => ({ ...prev, [docType]: { ...prev[docType], number: e.target.value } }))}
                    />
                    <div className="grid grid-cols-2 gap-2">
                      <div>
                        <Label className="text-xs text-muted-foreground">Front Image</Label>
                        <Input type="file" accept="image/*,.pdf" className="text-xs"
                          onChange={e => setKycUploads(prev => ({ ...prev, [docType]: { ...prev[docType], front: e.target.files?.[0] } }))}
                        />
                      </div>
                      <div>
                        <Label className="text-xs text-muted-foreground">Back Image</Label>
                        <Input type="file" accept="image/*,.pdf" className="text-xs"
                          onChange={e => setKycUploads(prev => ({ ...prev, [docType]: { ...prev[docType], back: e.target.files?.[0] } }))}
                        />
                      </div>
                    </div>
                  </div>
                ))}

                <Button className="w-full gap-2 h-11" onClick={handleKYCUpload} disabled={uploadingKyc}>
                  <Upload className="h-4 w-4" /> {uploadingKyc ? "Uploading..." : "Submit KYC Documents"}
                </Button>
              </CardContent>
            </Card>
          )}

          {kycDone && (
            <Card className="border-blue-200 bg-blue-50/50 dark:bg-blue-950/20 shadow-sm">
              <CardContent className="py-6 text-center">
                <ShieldCheck className="h-12 w-12 mx-auto text-blue-500 mb-3" />
                <h3 className="font-bold text-lg text-blue-700 dark:text-blue-300">KYC Documents Submitted!</h3>
                <p className="text-sm text-muted-foreground mt-1">Your documents are under verification. We'll confirm once approved.</p>
              </CardContent>
            </Card>
          )}

          {/* Footer */}
          <div className="text-center text-xs text-muted-foreground py-4 space-y-1">
            <p>© {new Date().getFullYear()} GrabYourCar • Self-Drive Rentals</p>
            <p>This is a legally binding digital agreement</p>
          </div>
        </div>
      </div>
    </SectionErrorBoundary>
  );
}

// ─── Sub-component ─────────────────────────────────────────────────
function DetailRow({ icon: Icon, label, value, highlight }: { icon: any; label: string; value: string; highlight?: boolean }) {
  return (
    <div className="flex items-center gap-2.5">
      <Icon className="h-4 w-4 text-muted-foreground shrink-0" />
      <div>
        <div className="text-[11px] text-muted-foreground">{label}</div>
        <div className={`font-medium text-sm ${highlight ? "text-primary font-bold" : ""}`}>{value}</div>
      </div>
    </div>
  );
}
