import { useState, useRef, useEffect, useCallback } from "react";
import { useParams } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { useAgreementByToken, useAddAgreementHistory } from "@/hooks/useRentalAgreements";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Skeleton } from "@/components/ui/skeleton";
import { SectionErrorBoundary } from "@/components/SectionErrorBoundary";
import { toast } from "sonner";
import { format } from "date-fns";
import {
  CheckCircle2, FileText, Pen, Type, Upload, ShieldCheck,
  Car, Phone, Calendar, MapPin, CreditCard, AlertTriangle, Download,
  ChevronRight, Eye, Clock, Sparkles,
} from "lucide-react";
import jsPDF from "jspdf";

// ─── helpers ───────────────────────────────────────────────────────
async function getClientIP(): Promise<string> {
  try {
    const res = await fetch("https://api.ipify.org?format=json");
    const data = await res.json();
    return data.ip || "unknown";
  } catch { return "unknown"; }
}

function getDeviceInfo(): string {
  try { return navigator.userAgent; } catch { return "unknown"; }
}

function generateSignedPDF(agreement: any, signatureName: string, signatureType: string, signatureData: string) {
  const doc = new jsPDF();
  const w = doc.internal.pageSize.getWidth();
  doc.setFontSize(18); doc.setFont("helvetica", "bold");
  doc.text("GrabYourCar", w / 2, 20, { align: "center" });
  doc.setFontSize(10); doc.setFont("helvetica", "normal");
  doc.text("Self-Drive Rental Agreement", w / 2, 27, { align: "center" });
  doc.setFontSize(8);
  doc.text(agreement.agreement_number || "", w / 2, 32, { align: "center" });
  doc.line(15, 36, w - 15, 36);
  let y = 44;
  doc.setFontSize(10);
  const details = [
    ["Customer", agreement.customer_name], ["Phone", agreement.customer_phone],
    ["Vehicle", `${agreement.vehicle_name || "N/A"} ${agreement.vehicle_number ? `(${agreement.vehicle_number})` : ""}`],
    ["Pickup Date", agreement.pickup_date || "N/A"], ["Dropoff Date", agreement.dropoff_date || "N/A"],
    ["Pickup Location", agreement.pickup_location || "N/A"], ["Dropoff Location", agreement.dropoff_location || "N/A"],
    ["Rental Amount", `Rs. ${(agreement.rental_amount || 0).toLocaleString("en-IN")}`],
    ["Security Deposit", `Rs. ${(agreement.security_deposit || 0).toLocaleString("en-IN")}`],
  ];
  details.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold"); doc.text(`${label}:`, 18, y);
    doc.setFont("helvetica", "normal"); doc.text(String(value), 65, y); y += 7;
  });
  y += 5; doc.line(15, y, w - 15, y); y += 8;
  doc.setFont("helvetica", "bold"); doc.text("Terms & Conditions", 18, y); y += 6;
  doc.setFont("helvetica", "normal"); doc.setFontSize(8);
  const plainTerms = agreement.terms_html.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim();
  const lines = doc.splitTextToSize(plainTerms, w - 36);
  lines.forEach((line: string) => {
    if (y > 260) { doc.addPage(); y = 20; }
    doc.text(line, 18, y); y += 4.5;
  });
  if (y > 230) { doc.addPage(); y = 20; }
  y += 10; doc.line(15, y, w - 15, y); y += 8;
  doc.setFontSize(11); doc.setFont("helvetica", "bold");
  doc.text("Digital Signature", 18, y); y += 8;
  doc.setFontSize(10); doc.setFont("helvetica", "normal");
  doc.text(`Signed by: ${signatureName}`, 18, y); y += 6;
  doc.text(`Method: ${signatureType === "draw" ? "Hand-drawn signature" : "Typed name"}`, 18, y); y += 6;
  doc.text(`Date: ${format(new Date(), "PPpp")}`, 18, y); y += 6;
  if (signatureType === "draw" && signatureData) {
    try { doc.addImage(signatureData, "PNG", 18, y, 80, 25); y += 30; } catch { /* skip */ }
  } else if (signatureType === "type") {
    y += 4; doc.setFontSize(20); doc.setFont("times", "italic");
    doc.text(signatureData, 18, y); y += 12;
  }
  doc.setFontSize(7); doc.setFont("helvetica", "normal");
  doc.text("This is a legally binding digital agreement. Generated by GrabYourCar.", w / 2, 285, { align: "center" });
  return doc;
}

// ─── Loading Skeleton ──────────────────────────────────────────────
function AgreementSkeleton() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-emerald-50 via-white to-cyan-50 py-8 px-4">
      <div className="max-w-lg mx-auto space-y-5">
        <Skeleton className="h-10 w-48 mx-auto rounded-full" />
        <Skeleton className="h-3 w-64 mx-auto" />
        <Skeleton className="h-12 w-full rounded-xl" />
        <Skeleton className="h-48 w-full rounded-xl" />
        <Skeleton className="h-32 w-full rounded-xl" />
      </div>
    </div>
  );
}

// ─── Error State ───────────────────────────────────────────────────
function AgreementError({ message }: { message?: string }) {
  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-red-50 to-orange-50 px-4">
      <Card className="max-w-sm w-full shadow-xl">
        <CardContent className="py-10 text-center">
          <AlertTriangle className="h-14 w-14 mx-auto mb-4 text-destructive" />
          <h2 className="text-lg font-bold">Agreement Not Found</h2>
          <p className="text-sm text-muted-foreground mt-2">
            {message || "This link may be expired or invalid."}
          </p>
          <p className="text-xs text-muted-foreground mt-4">Contact GrabYourCar support for help.</p>
        </CardContent>
      </Card>
    </div>
  );
}

// ─── Step Progress Bar ─────────────────────────────────────────────
const STEPS = [
  { id: 1, label: "Review", icon: Eye },
  { id: 2, label: "Agree", icon: CheckCircle2 },
  { id: 3, label: "Sign", icon: Pen },
  { id: 4, label: "Done", icon: Sparkles },
];

function StepProgress({ currentStep }: { currentStep: number }) {
  return (
    <div className="flex items-center justify-between w-full max-w-xs mx-auto">
      {STEPS.map((step, i) => {
        const Icon = step.icon;
        const isActive = currentStep === step.id;
        const isDone = currentStep > step.id;
        return (
          <div key={step.id} className="flex items-center">
            <div className="flex flex-col items-center">
              <div className={`
                w-9 h-9 rounded-full flex items-center justify-center text-xs font-bold transition-all duration-300
                ${isDone ? "bg-emerald-500 text-white scale-100" : ""}
                ${isActive ? "bg-primary text-primary-foreground scale-110 ring-4 ring-primary/20" : ""}
                ${!isDone && !isActive ? "bg-muted text-muted-foreground" : ""}
              `}>
                {isDone ? <CheckCircle2 className="h-4 w-4" /> : <Icon className="h-4 w-4" />}
              </div>
              <span className={`text-[10px] mt-1 font-medium ${isActive ? "text-primary" : isDone ? "text-emerald-600" : "text-muted-foreground"}`}>
                {step.label}
              </span>
            </div>
            {i < STEPS.length - 1 && (
              <div className={`w-8 sm:w-12 h-0.5 mx-1 transition-colors duration-300 ${isDone ? "bg-emerald-500" : "bg-muted"}`} />
            )}
          </div>
        );
      })}
    </div>
  );
}

// ─── Main Component ────────────────────────────────────────────────
export default function AgreementSignPage() {
  const { token } = useParams<{ token: string }>();
  const { data: agreement, isLoading, error, refetch } = useAgreementByToken(token || null);
  const addHistory = useAddAgreementHistory();

  // Wizard step: 1=Review, 2=Agree, 3=Sign, 4=Done
  const [step, setStep] = useState(1);
  const [signMode, setSignMode] = useState<"type" | "draw" | null>(null);
  const [typedName, setTypedName] = useState("");
  const [agreed, setAgreed] = useState(false);
  const [signing, setSigning] = useState(false);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [isDrawing, setIsDrawing] = useState(false);

  // KYC (optional step after signing)
  const [showKyc, setShowKyc] = useState(false);
  const [kycUploads, setKycUploads] = useState<Record<string, { front?: File; back?: File; number: string }>>({
    aadhaar: { number: "" }, driving_license: { number: "" },
    pan_card: { number: "" }, address_proof: { number: "" },
  });
  const [uploadingKyc, setUploadingKyc] = useState(false);
  const [kycDone, setKycDone] = useState(false);

  // If already signed, jump to done
  useEffect(() => {
    if (agreement?.client_signed_at) setStep(4);
  }, [agreement?.client_signed_at]);

  // Mark as viewed
  useEffect(() => {
    if (agreement && !agreement.client_viewed_at && agreement.status === "sent") {
      supabase.from("rental_agreements")
        .update({ client_viewed_at: new Date().toISOString(), status: "viewed" } as any)
        .eq("id", agreement.id)
        .then(() => {
          addHistory.mutate({
            agreement_id: agreement.id,
            action: "viewed_by_client",
            action_by: agreement.customer_name,
          });
        });
    }
  }, [agreement?.id]); // eslint-disable-line

  // Canvas setup
  useEffect(() => {
    if (signMode === "draw" && canvasRef.current) {
      const ctx = canvasRef.current.getContext("2d");
      if (ctx) { ctx.lineWidth = 2.5; ctx.strokeStyle = "#1a1a2e"; ctx.lineCap = "round"; }
    }
  }, [signMode]);

  const getPos = useCallback((e: React.MouseEvent | React.TouchEvent) => {
    const canvas = canvasRef.current;
    if (!canvas) return { x: 0, y: 0 };
    const rect = canvas.getBoundingClientRect();
    const scaleX = canvas.width / rect.width;
    const scaleY = canvas.height / rect.height;
    if ("touches" in e) {
      return { x: (e.touches[0].clientX - rect.left) * scaleX, y: (e.touches[0].clientY - rect.top) * scaleY };
    }
    return { x: (e.clientX - rect.left) * scaleX, y: (e.clientY - rect.top) * scaleY };
  }, []);

  const startDraw = useCallback((e: React.MouseEvent | React.TouchEvent) => {
    e.preventDefault(); setIsDrawing(true);
    const ctx = canvasRef.current?.getContext("2d");
    const { x, y } = getPos(e);
    ctx?.beginPath(); ctx?.moveTo(x, y);
  }, [getPos]);

  const draw = useCallback((e: React.MouseEvent | React.TouchEvent) => {
    if (!isDrawing) return; e.preventDefault();
    const ctx = canvasRef.current?.getContext("2d");
    const { x, y } = getPos(e);
    ctx?.lineTo(x, y); ctx?.stroke();
  }, [isDrawing, getPos]);

  const stopDraw = useCallback(() => setIsDrawing(false), []);

  const clearCanvas = useCallback(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    canvas.getContext("2d")?.clearRect(0, 0, canvas.width, canvas.height);
  }, []);

  // Handle Sign
  const handleSign = async () => {
    if (!agreement || !agreed) return;
    let sigData = "";
    if (signMode === "type") {
      if (!typedName.trim()) { toast.error("Please type your full name"); return; }
      sigData = typedName.trim();
    } else if (signMode === "draw") {
      const canvas = canvasRef.current;
      if (!canvas) return;
      sigData = canvas.toDataURL("image/png");
    } else {
      toast.error("Please select a signature method"); return;
    }

    setSigning(true);
    try {
      const [clientIP, userAgent] = await Promise.all([getClientIP(), Promise.resolve(getDeviceInfo())]);

      await supabase.from("rental_agreements").update({
        client_signed_at: new Date().toISOString(),
        client_signature_type: signMode,
        client_signature_data: sigData,
        client_signed_name: signMode === "type" ? typedName.trim() : agreement.customer_name,
        client_ip_address: clientIP,
        client_user_agent: userAgent,
        status: "signed",
      } as any).eq("id", agreement.id);

      await addHistory.mutateAsync({
        agreement_id: agreement.id,
        action: "signed_by_client",
        action_by: agreement.customer_name,
        details: { signature_type: signMode, ip: clientIP, device: userAgent.substring(0, 100) },
      });

      setStep(4);
      toast.success("🎉 Agreement signed successfully!");
      refetch();
    } catch (e: any) {
      toast.error("Signing failed: " + e.message);
    } finally {
      setSigning(false);
    }
  };

  // Download PDF
  const handleDownloadPDF = () => {
    if (!agreement) return;
    try {
      const doc = generateSignedPDF(
        agreement,
        agreement.client_signed_name || typedName || agreement.customer_name,
        agreement.client_signature_type || signMode || "type",
        agreement.client_signature_data || typedName || "",
      );
      doc.save(`${agreement.agreement_number || "agreement"}.pdf`);
      toast.success("PDF downloaded!");
    } catch { toast.error("PDF generation failed"); }
  };

  // KYC Upload
  const handleKYCUpload = async () => {
    if (!agreement) return;
    setUploadingKyc(true);
    try {
      for (const [docType, docData] of Object.entries(kycUploads)) {
        if (!docData.front && !docData.number) continue;
        let frontUrl = null, backUrl = null;
        if (docData.front) {
          const path = `${agreement.customer_phone}/${docType}_front_${Date.now()}`;
          const { error: upErr } = await supabase.storage.from("kyc-documents").upload(path, docData.front);
          if (!upErr) { frontUrl = supabase.storage.from("kyc-documents").getPublicUrl(path).data.publicUrl; }
        }
        if (docData.back) {
          const path = `${agreement.customer_phone}/${docType}_back_${Date.now()}`;
          const { error: upErr } = await supabase.storage.from("kyc-documents").upload(path, docData.back);
          if (!upErr) { backUrl = supabase.storage.from("kyc-documents").getPublicUrl(path).data.publicUrl; }
        }
        if (frontUrl || docData.number) {
          await supabase.from("rental_kyc_documents").insert([{
            agreement_id: agreement.id, customer_phone: agreement.customer_phone,
            customer_name: agreement.customer_name, document_type: docType,
            document_number: docData.number || null,
            document_front_url: frontUrl, document_back_url: backUrl,
            verification_status: "pending",
          }] as any);
        }
      }
      await addHistory.mutateAsync({ agreement_id: agreement.id, action: "kyc_uploaded", action_by: agreement.customer_name });
      setKycDone(true);
      toast.success("KYC documents uploaded!");
    } catch (e: any) {
      toast.error(e.message);
    } finally {
      setUploadingKyc(false);
    }
  };

  // ─── Render States ─────────────────────────────────────────────
  if (!token) return <AgreementError message="No agreement token provided in the URL." />;
  if (isLoading) return <AgreementSkeleton />;
  if (error || !agreement) return <AgreementError />;

  return (
    <SectionErrorBoundary sectionName="AgreementSignPage">
      <div className="min-h-screen bg-gradient-to-br from-emerald-50 via-white to-cyan-50 dark:from-gray-950 dark:to-gray-900">
        {/* Sticky Header */}
        <div className="sticky top-0 z-20 bg-white/80 dark:bg-gray-950/80 backdrop-blur-md border-b shadow-sm">
          <div className="max-w-lg mx-auto px-4 py-3">
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center">
                  <Car className="h-4 w-4 text-primary" />
                </div>
                <span className="font-bold text-sm text-primary" style={{ fontFamily: "'Outfit', sans-serif" }}>GrabYourCar</span>
              </div>
              <Badge variant="outline" className="text-[10px]">{agreement.agreement_number}</Badge>
            </div>
            <StepProgress currentStep={step} />
          </div>
        </div>

        <div className="max-w-lg mx-auto px-4 py-5 space-y-4">

          {/* ═══════════════ STEP 1: REVIEW ═══════════════ */}
          {step === 1 && (
            <div className="space-y-4 animate-in fade-in slide-in-from-right-4 duration-300">
              {/* Greeting */}
              <div className="text-center py-2">
                <h1 className="text-xl font-bold" style={{ fontFamily: "'Outfit', sans-serif" }}>
                  Hi {agreement.customer_name.split(" ")[0]} 👋
                </h1>
                <p className="text-sm text-muted-foreground mt-1">
                  Please review your rental booking details
                </p>
              </div>

              {/* Booking Card */}
              <Card className="shadow-md border-primary/15 overflow-hidden">
                <div className="bg-primary/5 px-4 py-2.5 border-b">
                  <h3 className="font-semibold text-sm flex items-center gap-2">
                    <FileText className="h-4 w-4 text-primary" /> Booking Details
                  </h3>
                </div>
                <CardContent className="py-4">
                  <div className="grid grid-cols-2 gap-3">
                    <DetailRow icon={Phone} label="Name" value={agreement.customer_name} />
                    <DetailRow icon={Phone} label="Phone" value={agreement.customer_phone} />
                    {agreement.vehicle_name && (
                      <DetailRow icon={Car} label="Vehicle" value={`${agreement.vehicle_name} ${agreement.vehicle_number ? `(${agreement.vehicle_number})` : ""}`} />
                    )}
                    {agreement.pickup_date && <DetailRow icon={Calendar} label="Pickup" value={agreement.pickup_date} />}
                    {agreement.dropoff_date && <DetailRow icon={Calendar} label="Dropoff" value={agreement.dropoff_date} />}
                    {agreement.pickup_location && <DetailRow icon={MapPin} label="From" value={agreement.pickup_location} />}
                    {agreement.dropoff_location && <DetailRow icon={MapPin} label="To" value={agreement.dropoff_location} />}
                  </div>

                  {/* Price highlight */}
                  <div className="mt-4 flex gap-3">
                    <div className="flex-1 bg-primary/5 rounded-xl p-3 text-center">
                      <div className="text-[10px] text-muted-foreground uppercase tracking-wider">Rental</div>
                      <div className="text-lg font-bold text-primary">₹{(agreement.rental_amount || 0).toLocaleString("en-IN")}</div>
                    </div>
                    <div className="flex-1 bg-amber-50 dark:bg-amber-950/20 rounded-xl p-3 text-center">
                      <div className="text-[10px] text-muted-foreground uppercase tracking-wider">Deposit</div>
                      <div className="text-lg font-bold text-amber-600">₹{(agreement.security_deposit || 0).toLocaleString("en-IN")}</div>
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Terms (collapsible) */}
              <Card className="shadow-sm">
                <CardContent className="py-4">
                  <h3 className="font-semibold text-sm mb-3 flex items-center gap-2">
                    <FileText className="h-4 w-4 text-primary" /> Terms & Conditions
                  </h3>
                  <div className="prose prose-sm max-w-none text-xs leading-relaxed max-h-48 overflow-y-auto pr-2 border rounded-lg p-3 bg-muted/30"
                    dangerouslySetInnerHTML={{ __html: agreement.terms_html }}
                  />
                </CardContent>
              </Card>

              {/* CTA */}
              <Button className="w-full h-12 text-base gap-2 shadow-lg" onClick={() => setStep(2)}>
                I've Reviewed — Continue <ChevronRight className="h-5 w-5" />
              </Button>
            </div>
          )}

          {/* ═══════════════ STEP 2: AGREE ═══════════════ */}
          {step === 2 && (
            <div className="space-y-4 animate-in fade-in slide-in-from-right-4 duration-300">
              <div className="text-center py-2">
                <h2 className="text-lg font-bold" style={{ fontFamily: "'Outfit', sans-serif" }}>Confirm Your Agreement</h2>
                <p className="text-sm text-muted-foreground mt-1">Please read and accept the terms</p>
              </div>

              <Card className="shadow-md">
                <CardContent className="py-5 space-y-4">
                  {/* Key terms summary */}
                  <div className="space-y-2.5">
                    {[
                      "Vehicle used exclusively by verified renter",
                      "Return on agreed date with same fuel level",
                      "Extra KM at ₹12/km beyond agreed limit",
                      "Late return penalty: ₹500/hour after 2hr grace",
                      "Security deposit refund within 3-5 business days",
                      "Insurance excess up to ₹15,000 in case of accident",
                    ].map((term, i) => (
                      <div key={i} className="flex items-start gap-2.5 text-sm">
                        <CheckCircle2 className="h-4 w-4 text-emerald-500 shrink-0 mt-0.5" />
                        <span>{term}</span>
                      </div>
                    ))}
                  </div>

                  <div className="border-t pt-4">
                    <div className="flex items-start gap-3 p-3 rounded-xl bg-primary/5 border border-primary/20">
                      <Checkbox id="agree" checked={agreed} onCheckedChange={(v) => setAgreed(v === true)} className="mt-0.5" />
                      <label htmlFor="agree" className="text-sm cursor-pointer leading-relaxed">
                        I have read, understood, and <strong>agree to all terms & conditions</strong> of this rental agreement.
                      </label>
                    </div>
                  </div>
                </CardContent>
              </Card>

              <div className="flex gap-2">
                <Button variant="outline" onClick={() => setStep(1)} className="flex-1">
                  ← Back
                </Button>
                <Button className="flex-1 h-12 text-base gap-2 shadow-lg" disabled={!agreed} onClick={() => setStep(3)}>
                  Agree & Sign <ChevronRight className="h-5 w-5" />
                </Button>
              </div>
            </div>
          )}

          {/* ═══════════════ STEP 3: SIGN ═══════════════ */}
          {step === 3 && (
            <div className="space-y-4 animate-in fade-in slide-in-from-right-4 duration-300">
              <div className="text-center py-2">
                <h2 className="text-lg font-bold" style={{ fontFamily: "'Outfit', sans-serif" }}>Add Your Signature</h2>
                <p className="text-sm text-muted-foreground mt-1">Choose how you'd like to sign</p>
              </div>

              <Card className="shadow-md">
                <CardContent className="py-5 space-y-4">
                  {/* Signature method selector */}
                  <div className="grid grid-cols-2 gap-2">
                    <button
                      onClick={() => setSignMode("type")}
                      className={`p-4 rounded-xl border-2 text-center transition-all ${
                        signMode === "type"
                          ? "border-primary bg-primary/5 shadow-md"
                          : "border-muted hover:border-primary/40"
                      }`}
                    >
                      <Type className="h-6 w-6 mx-auto mb-1.5 text-primary" />
                      <div className="text-sm font-semibold">Type Name</div>
                      <div className="text-[10px] text-muted-foreground">Quick & easy</div>
                    </button>
                    <button
                      onClick={() => setSignMode("draw")}
                      className={`p-4 rounded-xl border-2 text-center transition-all ${
                        signMode === "draw"
                          ? "border-primary bg-primary/5 shadow-md"
                          : "border-muted hover:border-primary/40"
                      }`}
                    >
                      <Pen className="h-6 w-6 mx-auto mb-1.5 text-primary" />
                      <div className="text-sm font-semibold">Draw Signature</div>
                      <div className="text-[10px] text-muted-foreground">Hand-drawn</div>
                    </button>
                  </div>

                  {/* Type signature */}
                  {signMode === "type" && (
                    <div className="space-y-3 animate-in fade-in duration-200">
                      <Label className="text-sm">Your full legal name</Label>
                      <Input
                        value={typedName}
                        onChange={e => setTypedName(e.target.value)}
                        placeholder="e.g. Rahul Kumar Sharma"
                        className="h-11 text-base"
                        autoFocus
                      />
                      {typedName && (
                        <div className="p-5 border-2 border-dashed rounded-xl bg-white text-center">
                          <span className="text-3xl italic font-serif text-black">{typedName}</span>
                          <p className="text-[10px] text-muted-foreground mt-2">Preview of your digital signature</p>
                        </div>
                      )}
                    </div>
                  )}

                  {/* Draw signature */}
                  {signMode === "draw" && (
                    <div className="space-y-2 animate-in fade-in duration-200">
                      <Label className="text-sm">Draw your signature below</Label>
                      <canvas
                        ref={canvasRef} width={600} height={200}
                        className="border-2 border-dashed rounded-xl w-full bg-white cursor-crosshair touch-none"
                        style={{ height: "160px" }}
                        onMouseDown={startDraw} onMouseMove={draw} onMouseUp={stopDraw} onMouseLeave={stopDraw}
                        onTouchStart={startDraw} onTouchMove={draw} onTouchEnd={stopDraw}
                      />
                      <div className="flex justify-end">
                        <Button variant="ghost" size="sm" onClick={clearCanvas} className="text-xs text-muted-foreground">
                          Clear & Redraw
                        </Button>
                      </div>
                    </div>
                  )}
                </CardContent>
              </Card>

              {signMode && (
                <div className="space-y-2">
                  <Button
                    className="w-full h-14 text-lg gap-2 shadow-xl bg-emerald-600 hover:bg-emerald-700"
                    onClick={handleSign}
                    disabled={signing || (signMode === "type" && !typedName.trim())}
                  >
                    {signing ? (
                      <><Clock className="h-5 w-5 animate-spin" /> Signing...</>
                    ) : (
                      <><CheckCircle2 className="h-5 w-5" /> Submit & Sign Agreement</>
                    )}
                  </Button>
                  <p className="text-[10px] text-center text-muted-foreground">
                    By signing, your IP address and device info will be recorded for verification.
                  </p>
                </div>
              )}

              <Button variant="ghost" onClick={() => setStep(2)} className="w-full text-muted-foreground">
                ← Go Back
              </Button>
            </div>
          )}

          {/* ═══════════════ STEP 4: DONE ═══════════════ */}
          {step === 4 && (
            <div className="space-y-4 animate-in fade-in slide-in-from-bottom-4 duration-500">
              <Card className="border-emerald-300 bg-emerald-50/60 dark:bg-emerald-950/20 shadow-xl overflow-hidden">
                <div className="bg-emerald-500 py-6 text-center text-white">
                  <CheckCircle2 className="h-16 w-16 mx-auto mb-3 drop-shadow-lg" />
                  <h2 className="text-2xl font-bold" style={{ fontFamily: "'Outfit', sans-serif" }}>Agreement Signed! 🎉</h2>
                  <p className="text-emerald-100 text-sm mt-1">Your booking is confirmed</p>
                </div>
                <CardContent className="py-5 space-y-4">
                  {/* Signed info */}
                  <div className="text-center text-sm space-y-1">
                    <p>Signed by <strong>{agreement.client_signed_name || typedName || agreement.customer_name}</strong></p>
                    <p className="text-xs text-muted-foreground">
                      {agreement.client_signed_at
                        ? format(new Date(agreement.client_signed_at), "PPpp")
                        : format(new Date(), "PPpp")}
                    </p>
                  </div>

                  {/* Show signature */}
                  {agreement.client_signature_type === "draw" && agreement.client_signature_data && (
                    <div className="flex justify-center">
                      <div className="bg-white border-2 rounded-xl p-3 shadow-sm">
                        <img src={agreement.client_signature_data} alt="Signature" className="h-14" />
                      </div>
                    </div>
                  )}
                  {agreement.client_signature_type === "type" && agreement.client_signature_data && (
                    <div className="flex justify-center">
                      <div className="bg-white border-2 rounded-xl px-6 py-3 shadow-sm">
                        <span className="text-2xl italic font-serif text-black">{agreement.client_signature_data}</span>
                      </div>
                    </div>
                  )}

                  {/* Booking summary */}
                  <div className="bg-muted/50 rounded-xl p-3 space-y-2 text-sm">
                    <div className="flex justify-between"><span className="text-muted-foreground">Vehicle</span><span className="font-medium">{agreement.vehicle_name || "TBD"}</span></div>
                    {agreement.pickup_date && <div className="flex justify-between"><span className="text-muted-foreground">Pickup</span><span className="font-medium">{agreement.pickup_date}</span></div>}
                    {agreement.dropoff_date && <div className="flex justify-between"><span className="text-muted-foreground">Dropoff</span><span className="font-medium">{agreement.dropoff_date}</span></div>}
                    <div className="flex justify-between border-t pt-2"><span className="text-muted-foreground">Amount</span><span className="font-bold text-primary">₹{(agreement.rental_amount || 0).toLocaleString("en-IN")}</span></div>
                  </div>

                  {/* Actions */}
                  <div className="flex flex-col gap-2">
                    <Button className="w-full gap-2 h-11" variant="outline" onClick={handleDownloadPDF}>
                      <Download className="h-4 w-4" /> Download Signed PDF
                    </Button>
                    {!showKyc && !kycDone && (
                      <Button className="w-full gap-2 h-11" onClick={() => setShowKyc(true)}>
                        <Upload className="h-4 w-4" /> Upload KYC Documents
                      </Button>
                    )}
                  </div>
                </CardContent>
              </Card>

              {/* KYC Section */}
              {showKyc && !kycDone && (
                <Card className="shadow-md animate-in fade-in slide-in-from-bottom-2 duration-300">
                  <CardContent className="py-5 space-y-4">
                    <div className="flex items-center gap-2">
                      <ShieldCheck className="h-5 w-5 text-primary" />
                      <h3 className="font-semibold text-sm" style={{ fontFamily: "'Outfit', sans-serif" }}>KYC Verification</h3>
                    </div>
                    <p className="text-xs text-muted-foreground">Upload documents for identity verification before pickup.</p>

                    {(["aadhaar", "driving_license", "pan_card", "address_proof"] as const).map(docType => (
                      <div key={docType} className="border rounded-xl p-3 space-y-2">
                        <Label className="text-sm font-medium capitalize">{docType.replace(/_/g, " ")}</Label>
                        <Input
                          placeholder={`${docType.replace(/_/g, " ")} number`}
                          value={kycUploads[docType]?.number || ""}
                          onChange={e => setKycUploads(prev => ({ ...prev, [docType]: { ...prev[docType], number: e.target.value } }))}
                        />
                        <div className="grid grid-cols-2 gap-2">
                          <div>
                            <Label className="text-xs text-muted-foreground">Front</Label>
                            <Input type="file" accept="image/*,.pdf" className="text-xs"
                              onChange={e => setKycUploads(prev => ({ ...prev, [docType]: { ...prev[docType], front: e.target.files?.[0] } }))}
                            />
                          </div>
                          <div>
                            <Label className="text-xs text-muted-foreground">Back</Label>
                            <Input type="file" accept="image/*,.pdf" className="text-xs"
                              onChange={e => setKycUploads(prev => ({ ...prev, [docType]: { ...prev[docType], back: e.target.files?.[0] } }))}
                            />
                          </div>
                        </div>
                      </div>
                    ))}

                    <Button className="w-full gap-2 h-11" onClick={handleKYCUpload} disabled={uploadingKyc}>
                      <Upload className="h-4 w-4" /> {uploadingKyc ? "Uploading..." : "Submit KYC Documents"}
                    </Button>
                  </CardContent>
                </Card>
              )}

              {kycDone && (
                <Card className="border-blue-200 bg-blue-50/50 dark:bg-blue-950/20 shadow-md">
                  <CardContent className="py-5 text-center">
                    <ShieldCheck className="h-10 w-10 mx-auto text-blue-500 mb-2" />
                    <h3 className="font-bold text-blue-700 dark:text-blue-300">KYC Submitted!</h3>
                    <p className="text-xs text-muted-foreground mt-1">We'll verify your documents before pickup.</p>
                  </CardContent>
                </Card>
              )}

              {/* WhatsApp support */}
              <div className="text-center pt-2">
                <p className="text-xs text-muted-foreground mb-2">Need help?</p>
                <Button variant="outline" size="sm" className="gap-2 text-xs"
                  onClick={() => window.open("https://wa.me/919876543210?text=Hi, I just signed my rental agreement", "_blank")}>
                  💬 Chat with us on WhatsApp
                </Button>
              </div>
            </div>
          )}

          {/* Footer */}
          <div className="text-center text-[10px] text-muted-foreground py-6 space-y-0.5">
            <p>© {new Date().getFullYear()} GrabYourCar • Self-Drive Rentals</p>
            <p>Legally binding digital agreement</p>
          </div>
        </div>
      </div>
    </SectionErrorBoundary>
  );
}

// ─── Sub-component ─────────────────────────────────────────────────
function DetailRow({ icon: Icon, label, value }: { icon: any; label: string; value: string }) {
  return (
    <div className="flex items-center gap-2.5">
      <Icon className="h-4 w-4 text-muted-foreground shrink-0" />
      <div>
        <div className="text-[10px] text-muted-foreground">{label}</div>
        <div className="font-medium text-sm">{value}</div>
      </div>
    </div>
  );
}
