
-- Team monthly targets set by super admin
CREATE TABLE public.team_targets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  team_member_name TEXT NOT NULL,
  vertical_name TEXT NOT NULL,
  month_year TEXT NOT NULL,
  target_type TEXT NOT NULL DEFAULT 'deals',
  target_count INTEGER DEFAULT 0,
  target_revenue NUMERIC DEFAULT 0,
  achieved_count INTEGER DEFAULT 0,
  achieved_revenue NUMERIC DEFAULT 0,
  achievement_pct NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'active',
  set_by TEXT DEFAULT 'super_admin',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, vertical_name, month_year)
);

-- Team problems/blockers reported to AI and escalated to founder
CREATE TABLE public.team_problems (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  reported_by_user_id UUID,
  reported_by_name TEXT NOT NULL,
  vertical_name TEXT,
  problem_description TEXT NOT NULL,
  ai_solution TEXT,
  ai_solved BOOLEAN DEFAULT false,
  escalated_to_founder BOOLEAN DEFAULT false,
  founder_response TEXT,
  status TEXT DEFAULT 'open',
  priority TEXT DEFAULT 'medium',
  created_at TIMESTAMPTZ DEFAULT now(),
  resolved_at TIMESTAMPTZ
);

-- Weekly/monthly performance reports generated by AI
CREATE TABLE public.ai_performance_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  report_type TEXT NOT NULL DEFAULT 'weekly',
  period TEXT NOT NULL,
  vertical_name TEXT,
  user_id UUID,
  team_member_name TEXT,
  report_content TEXT NOT NULL,
  key_metrics JSONB,
  recommendations JSONB,
  incentive_suggestion JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Daily push notifications / reminders log
CREATE TABLE public.ai_daily_pushes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID,
  team_member_name TEXT NOT NULL,
  push_type TEXT NOT NULL,
  message TEXT NOT NULL,
  vertical_name TEXT,
  action_url TEXT,
  is_read BOOLEAN DEFAULT false,
  is_actioned BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.team_targets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_problems ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_performance_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_daily_pushes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage team_targets" ON public.team_targets FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can manage team_problems" ON public.team_problems FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can manage ai_performance_reports" ON public.ai_performance_reports FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can manage ai_daily_pushes" ON public.ai_daily_pushes FOR ALL TO authenticated USING (true) WITH CHECK (true);

ALTER PUBLICATION supabase_realtime ADD TABLE public.team_targets;
ALTER PUBLICATION supabase_realtime ADD TABLE public.team_problems;
ALTER PUBLICATION supabase_realtime ADD TABLE public.ai_daily_pushes;
