
-- AI-detected risk indicators across all verticals
CREATE TABLE public.ai_risk_indicators (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  risk_type TEXT NOT NULL,
  severity TEXT NOT NULL DEFAULT 'medium',
  vertical_name TEXT,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  impact_amount NUMERIC DEFAULT 0,
  recommended_action TEXT,
  auto_resolved BOOLEAN DEFAULT false,
  resolved_at TIMESTAMPTZ,
  founder_notified BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Cross-sell recommendations generated by AI
CREATE TABLE public.ai_cross_sell_suggestions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_name TEXT NOT NULL,
  customer_phone TEXT,
  source_vertical TEXT NOT NULL,
  target_vertical TEXT NOT NULL,
  suggestion TEXT NOT NULL,
  potential_revenue NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'pending',
  approved_by TEXT,
  actioned_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Investor contacts and outreach tracking
CREATE TABLE public.investor_contacts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  investor_name TEXT NOT NULL,
  firm_name TEXT,
  email TEXT,
  phone TEXT,
  linkedin_url TEXT,
  investment_stage TEXT,
  sector_focus TEXT,
  typical_ticket_size TEXT,
  status TEXT DEFAULT 'identified',
  last_contacted_at TIMESTAMPTZ,
  response TEXT,
  notes TEXT,
  ai_suggested BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- AI-detected mistakes and improvement suggestions
CREATE TABLE public.ai_mistake_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  mistake_type TEXT NOT NULL,
  vertical_name TEXT,
  team_member_name TEXT,
  description TEXT NOT NULL,
  impact TEXT,
  ai_fix_suggestion TEXT,
  status TEXT DEFAULT 'detected',
  founder_acknowledged BOOLEAN DEFAULT false,
  fixed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Business runway and financial health tracking
CREATE TABLE public.ai_runway_snapshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  snapshot_date DATE NOT NULL DEFAULT CURRENT_DATE,
  total_revenue NUMERIC DEFAULT 0,
  total_expenses NUMERIC DEFAULT 0,
  net_profit NUMERIC DEFAULT 0,
  cash_in_bank NUMERIC DEFAULT 0,
  monthly_burn_rate NUMERIC DEFAULT 0,
  runway_months NUMERIC DEFAULT 0,
  revenue_growth_pct NUMERIC DEFAULT 0,
  expense_growth_pct NUMERIC DEFAULT 0,
  ai_assessment TEXT,
  ai_recommendations JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.ai_risk_indicators ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_cross_sell_suggestions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.investor_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_mistake_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_runway_snapshots ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Auth users manage ai_risk_indicators" ON public.ai_risk_indicators FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Auth users manage ai_cross_sell_suggestions" ON public.ai_cross_sell_suggestions FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Auth users manage investor_contacts" ON public.investor_contacts FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Auth users manage ai_mistake_logs" ON public.ai_mistake_logs FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Auth users manage ai_runway_snapshots" ON public.ai_runway_snapshots FOR ALL TO authenticated USING (true) WITH CHECK (true);

ALTER PUBLICATION supabase_realtime ADD TABLE public.ai_risk_indicators;
ALTER PUBLICATION supabase_realtime ADD TABLE public.ai_cross_sell_suggestions;
ALTER PUBLICATION supabase_realtime ADD TABLE public.ai_mistake_logs;
