-- Seed default Chart of Accounts if empty
INSERT INTO public.chart_of_accounts (account_code, account_name, account_type, description, normal_side, current_balance)
SELECT code, name, type, desc_text, side, 0::numeric FROM (VALUES
  ('1000', 'Cash in Hand', 'asset', 'Physical cash', 'debit'),
  ('1010', 'Bank Account - HDFC', 'asset', 'Primary bank account', 'debit'),
  ('1020', 'Bank Account - ICICI', 'asset', 'Secondary bank account', 'debit'),
  ('1100', 'Accounts Receivable', 'asset', 'Money owed by customers', 'debit'),
  ('1200', 'Inventory - Vehicles', 'asset', 'Vehicle stock value', 'debit'),
  ('1300', 'Prepaid Expenses', 'asset', 'Advance payments', 'debit'),
  ('1400', 'Fixed Assets - Office Equipment', 'asset', 'Office equipment', 'debit'),
  ('1410', 'Fixed Assets - Vehicles', 'asset', 'Company vehicles', 'debit'),
  ('2000', 'Accounts Payable', 'liability', 'Money owed to suppliers', 'credit'),
  ('2100', 'GST Payable - CGST', 'liability', 'Central GST liability', 'credit'),
  ('2110', 'GST Payable - SGST', 'liability', 'State GST liability', 'credit'),
  ('2200', 'TDS Payable', 'liability', 'Tax deducted at source', 'credit'),
  ('2300', 'PF Payable', 'liability', 'Provident fund liability', 'credit'),
  ('2310', 'ESI Payable', 'liability', 'ESI liability', 'credit'),
  ('2400', 'Salary Payable', 'liability', 'Unpaid salaries', 'credit'),
  ('2500', 'Loan - Term Loan', 'liability', 'Bank term loan', 'credit'),
  ('3000', 'Capital Account', 'equity', 'Owner capital', 'credit'),
  ('3100', 'Retained Earnings', 'equity', 'Accumulated profits', 'credit'),
  ('4000', 'Sales Revenue - Car Sales', 'revenue', 'Revenue from car sales', 'credit'),
  ('4010', 'Revenue - Insurance Commission', 'revenue', 'Insurance commissions', 'credit'),
  ('4020', 'Revenue - HSRP Services', 'revenue', 'HSRP revenue', 'credit'),
  ('4030', 'Revenue - Self-Drive Rentals', 'revenue', 'Rental income', 'credit'),
  ('4040', 'Revenue - Accessories', 'revenue', 'Accessories sales', 'credit'),
  ('4050', 'Revenue - Car Loans', 'revenue', 'Loan processing fees', 'credit'),
  ('4060', 'Revenue - Corporate Fleet', 'revenue', 'Corporate fleet revenue', 'credit'),
  ('4100', 'Other Income', 'revenue', 'Miscellaneous income', 'credit'),
  ('5000', 'Cost of Goods Sold', 'expense', 'Direct cost of vehicles', 'debit'),
  ('5100', 'Salary Expense', 'expense', 'Employee salaries', 'debit'),
  ('5110', 'Employer PF Contribution', 'expense', 'PF employer share', 'debit'),
  ('5200', 'Rent Expense', 'expense', 'Office rent', 'debit'),
  ('5210', 'Electricity and Utilities', 'expense', 'Utility bills', 'debit'),
  ('5300', 'Marketing and Advertising', 'expense', 'Marketing spend', 'debit'),
  ('5400', 'Vehicle Maintenance', 'expense', 'Fleet maintenance', 'debit'),
  ('5500', 'Insurance Expense', 'expense', 'Company insurance', 'debit'),
  ('5600', 'Professional Fees', 'expense', 'Legal and accounting', 'debit'),
  ('5700', 'Office Supplies', 'expense', 'Stationery etc', 'debit'),
  ('5800', 'Travel and Conveyance', 'expense', 'Travel expenses', 'debit'),
  ('5900', 'Depreciation', 'expense', 'Asset depreciation', 'debit'),
  ('5950', 'Bank Charges', 'expense', 'Bank fees', 'debit'),
  ('5999', 'Miscellaneous Expense', 'expense', 'Other expenses', 'debit')
) AS v(code, name, type, desc_text, side)
WHERE NOT EXISTS (SELECT 1 FROM public.chart_of_accounts LIMIT 1)