
-- Add deep journey tracking, abandonment, document management, and handover fields
ALTER TABLE public.rental_bookings 
  ADD COLUMN IF NOT EXISTS website_journey jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS is_abandoned boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS abandoned_at timestamptz,
  ADD COLUMN IF NOT EXISTS abandoned_step text,
  ADD COLUMN IF NOT EXISTS recovery_attempted boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS recovery_attempted_at timestamptz,
  ADD COLUMN IF NOT EXISTS utm_source text,
  ADD COLUMN IF NOT EXISTS utm_medium text,
  ADD COLUMN IF NOT EXISTS utm_campaign text,
  ADD COLUMN IF NOT EXISTS page_referrer text,
  ADD COLUMN IF NOT EXISTS session_duration_seconds integer,
  ADD COLUMN IF NOT EXISTS documents_status jsonb DEFAULT '{"dl": "pending", "aadhaar": "pending", "address_proof": "pending", "selfie": "pending"}'::jsonb,
  ADD COLUMN IF NOT EXISTS dl_front_url text,
  ADD COLUMN IF NOT EXISTS dl_back_url text,
  ADD COLUMN IF NOT EXISTS aadhaar_front_url text,
  ADD COLUMN IF NOT EXISTS aadhaar_back_url text,
  ADD COLUMN IF NOT EXISTS selfie_url text,
  ADD COLUMN IF NOT EXISTS address_proof_url text,
  ADD COLUMN IF NOT EXISTS kyc_verified boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS kyc_verified_at timestamptz,
  ADD COLUMN IF NOT EXISTS kyc_verified_by text,
  ADD COLUMN IF NOT EXISTS handover_photos text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS return_photos text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS odometer_start integer,
  ADD COLUMN IF NOT EXISTS odometer_end integer,
  ADD COLUMN IF NOT EXISTS fuel_level_start text,
  ADD COLUMN IF NOT EXISTS fuel_level_end text,
  ADD COLUMN IF NOT EXISTS damage_report jsonb,
  ADD COLUMN IF NOT EXISTS damage_charges numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS extra_km_charges numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS late_return_charges numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS final_settlement_amount numeric,
  ADD COLUMN IF NOT EXISTS deposit_refund_status text DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS deposit_refund_amount numeric,
  ADD COLUMN IF NOT EXISTS handover_at timestamptz,
  ADD COLUMN IF NOT EXISTS returned_at timestamptz,
  ADD COLUMN IF NOT EXISTS handover_by text,
  ADD COLUMN IF NOT EXISTS return_inspected_by text,
  ADD COLUMN IF NOT EXISTS picked_up_by text,
  ADD COLUMN IF NOT EXISTS assigned_vehicle_number text,
  ADD COLUMN IF NOT EXISTS assigned_vehicle_color text;
