/**
 * Founder report PDF helpers.
 *  - openHtmlPrint(html, title): opens hidden window and triggers print
 *  - buildRowInvoice(args): single-record net-payout invoice
 *  - buildMonthlyStatement(args): consolidated monthly statement
 */

import { inr } from "./payoutEngine";

const esc = (v: any) =>
  String(v ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

const css = `
  @page { size: A4; margin: 14mm; }
  body { font-family: "Helvetica Neue", Arial, sans-serif; color:#0f172a; font-size:12px; }
  h1 { font-size:20px; margin:0 0 4px; font-family: Georgia, serif; color:#0f172a;}
  h2 { font-size:14px; margin:18px 0 6px; padding-bottom:4px; border-bottom:1px solid #e2e8f0; color:#1e293b; font-family:Georgia,serif;}
  .muted { color:#64748b; font-size:11px;}
  .pill{display:inline-block;padding:2px 8px;border-radius:999px;font-size:10px;font-weight:600;}
  table{width:100%;border-collapse:collapse;margin-top:6px;}
  th,td{border:1px solid #e2e8f0;padding:6px 8px;text-align:left;vertical-align:top;}
  th{background:#f1f5f9;font-size:10px;text-transform:uppercase;letter-spacing:0.04em;color:#475569;}
  td.num{text-align:right;font-variant-numeric:tabular-nums;}
  .totals td{background:#f8fafc;font-weight:700;}
  .stamp{margin-top:24px;padding:10px 12px;border:1px dashed #cbd5e1;border-radius:6px;background:#f8fafc;}
  .grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px;}
  .box{border:1px solid #e2e8f0;border-radius:6px;padding:8px 10px;background:#fff;}
  .lbl{font-size:10px;text-transform:uppercase;color:#64748b;letter-spacing:0.04em;}
  .val{font-size:13px;font-weight:600;margin-top:2px;}
`;

export function openHtmlPrint(html: string, title = "Report") {
  const w = window.open("", "_blank", "width=900,height=700");
  if (!w) {
    alert("Please allow pop-ups to download / print the report.");
    return;
  }
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"/><title>${esc(title)}</title><style>${css}</style></head><body>${html}<script>window.addEventListener('load',()=>setTimeout(()=>{window.print();},250));</script></body></html>`);
  w.document.close();
}

/* ============== Per-record net-payout invoice ============== */

export function buildRowInvoice(opts: {
  module: "insurance" | "loan" | "deal";
  reference: string;
  customer: string;
  meta: Array<[string, string]>;
  base: { label: string; amount: number };
  pct: number;
  gross: number;
  tds: number;
  net: number;
  notes?: string;
}) {
  const { module, reference, customer, meta, base, pct, gross, tds, net, notes } = opts;
  const moduleLabel = module === "insurance" ? "Insurance Policy" : module === "loan" ? "Car Loan" : "Automotive Deal";
  const html = `
    <h1>Net Payout Statement — ${esc(moduleLabel)}</h1>
    <p class="muted">Reference: <b>${esc(reference)}</b> · Generated ${new Date().toLocaleString("en-IN")}</p>
    <div class="grid">
      <div class="box"><div class="lbl">Customer</div><div class="val">${esc(customer)}</div></div>
      ${meta.map(([k,v]) => `<div class="box"><div class="lbl">${esc(k)}</div><div class="val">${esc(v)}</div></div>`).join("")}
    </div>
    <h2>Payout Breakup</h2>
    <table>
      <tr><th>Component</th><th>Basis</th><th class="num">Amount</th></tr>
      <tr><td>${esc(base.label)}</td><td>Source value</td><td class="num">${inr(base.amount)}</td></tr>
      <tr><td>Gross Payout</td><td>${pct}% of base</td><td class="num">${inr(gross)}</td></tr>
      <tr><td>TDS @ 5%</td><td>Statutory deduction</td><td class="num">- ${inr(tds)}</td></tr>
      <tr class="totals"><td colspan="2">Net Payout (Receivable)</td><td class="num">${inr(net)}</td></tr>
    </table>
    ${notes ? `<div class="stamp"><b>Notes:</b> ${esc(notes)}</div>` : ""}
    <div class="stamp">Auto-generated by Finance Office · GYC. All figures derived from live system data.</div>
  `;
  openHtmlPrint(html, `Payout - ${reference}`);
}

/* ============== Monthly consolidated statement ============== */

export function buildMonthlyStatement(opts: {
  monthLabel: string;
  module: "insurance" | "loan" | "deal";
  rows: Array<{
    date: string;
    reference: string;
    customer: string;
    productOrType: string;
    base: number;
    pct: number;
    gross: number;
    tds: number;
    net: number;
  }>;
}) {
  const { monthLabel, module, rows } = opts;
  const moduleLabel = module === "insurance" ? "Insurance" : module === "loan" ? "Car Loans" : "Automotive Deals";
  const sum = rows.reduce(
    (a, r) => ({ base: a.base + r.base, gross: a.gross + r.gross, tds: a.tds + r.tds, net: a.net + r.net }),
    { base: 0, gross: 0, tds: 0, net: 0 },
  );
  const html = `
    <h1>${esc(moduleLabel)} Monthly Statement</h1>
    <p class="muted">Period: <b>${esc(monthLabel)}</b> · Records: <b>${rows.length}</b> · Generated ${new Date().toLocaleString("en-IN")}</p>
    <h2>Records</h2>
    <table>
      <tr>
        <th>#</th><th>Date</th><th>Reference</th><th>Customer</th><th>Type</th>
        <th class="num">Base</th><th class="num">%</th><th class="num">Gross</th><th class="num">TDS</th><th class="num">Net</th>
      </tr>
      ${rows.map((r,i) => `
        <tr>
          <td>${i+1}</td>
          <td>${esc(r.date)}</td>
          <td>${esc(r.reference)}</td>
          <td>${esc(r.customer)}</td>
          <td>${esc(r.productOrType)}</td>
          <td class="num">${inr(r.base)}</td>
          <td class="num">${r.pct.toFixed(2)}%</td>
          <td class="num">${inr(r.gross)}</td>
          <td class="num">${inr(r.tds)}</td>
          <td class="num">${inr(r.net)}</td>
        </tr>`).join("")}
      <tr class="totals">
        <td colspan="5">TOTAL</td>
        <td class="num">${inr(sum.base)}</td>
        <td class="num">—</td>
        <td class="num">${inr(sum.gross)}</td>
        <td class="num">${inr(sum.tds)}</td>
        <td class="num">${inr(sum.net)}</td>
      </tr>
    </table>
    <div class="stamp">Auto-generated by Finance Office · GYC. Founder consolidated statement.</div>
  `;
  openHtmlPrint(html, `${moduleLabel}-Statement-${monthLabel}`);
}
