/**
 * Founder report PDF helpers.
 *
 *  - All downloadable PDFs are produced via the **UnifiedPdfRenderer** (jsPDF
 *    + jspdf-autotable + resolved branding). Logo, watermark, brand colors,
 *    fonts, and footer are applied automatically — no html2canvas, no print
 *    dialog, no popup blockers.
 *  - HTML / CSV builders remain for email payloads and screen previews.
 */

import { inr } from "./payoutEngine";
import { createRenderer } from "@/lib/pdf/UnifiedPdfRenderer";
import autoTable from "jspdf-autotable";
import { hexToRgb } from "@/lib/pdf/colorUtils";

const esc = (v: any) =>
  String(v ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

const css = `
  @page { size: A4; margin: 14mm; }
  body { font-family: "Helvetica Neue", Arial, sans-serif; color:#0f172a; font-size:12px; }
  h1 { font-size:20px; margin:0 0 4px; font-family: Georgia, serif; color:#0f172a;}
  h2 { font-size:14px; margin:18px 0 6px; padding-bottom:4px; border-bottom:1px solid #e2e8f0; color:#1e293b; font-family:Georgia,serif;}
  .muted { color:#64748b; font-size:11px;}
  .pill{display:inline-block;padding:2px 8px;border-radius:999px;font-size:10px;font-weight:600;}
  table{width:100%;border-collapse:collapse;margin-top:6px;}
  th,td{border:1px solid #e2e8f0;padding:6px 8px;text-align:left;vertical-align:top;}
  th{background:#f1f5f9;font-size:10px;text-transform:uppercase;letter-spacing:0.04em;color:#475569;}
  td.num{text-align:right;font-variant-numeric:tabular-nums;}
  .totals td{background:#f8fafc;font-weight:700;}
  .stamp{margin-top:24px;padding:10px 12px;border:1px dashed #cbd5e1;border-radius:6px;background:#f8fafc;}
  .grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px;}
  .box{border:1px solid #e2e8f0;border-radius:6px;padding:8px 10px;background:#fff;}
  .lbl{font-size:10px;text-transform:uppercase;color:#64748b;letter-spacing:0.04em;}
  .val{font-size:13px;font-weight:600;margin-top:2px;}
`;

export function openHtmlPrint(html: string, title = "Report") {
  const w = window.open("", "_blank", "width=900,height=700");
  if (!w) {
    alert("Please allow pop-ups to download / print the report.");
    return;
  }
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"/><title>${esc(title)}</title><style>${css}</style></head><body>${html}<script>window.addEventListener('load',()=>setTimeout(()=>{window.print();},250));</script></body></html>`);
  w.document.close();
}

/* ============== Per-record net-payout invoice ============== */

export function buildRowInvoice(opts: {
  module: "insurance" | "loan" | "deal";
  reference: string;
  customer: string;
  meta: Array<[string, string]>;
  base: { label: string; amount: number };
  pct: number;
  gross: number;
  tds: number;
  net: number;
  notes?: string;
}) {
  const { module, reference, customer, meta, base, pct, gross, tds, net, notes } = opts;
  const moduleLabel = module === "insurance" ? "Insurance Policy" : module === "loan" ? "Car Loan" : "Automotive Deal";
  const html = `
    <h1>Net Payout Statement — ${esc(moduleLabel)}</h1>
    <p class="muted">Reference: <b>${esc(reference)}</b> · Generated ${new Date().toLocaleString("en-IN")}</p>
    <div class="grid">
      <div class="box"><div class="lbl">Customer</div><div class="val">${esc(customer)}</div></div>
      ${meta.map(([k,v]) => `<div class="box"><div class="lbl">${esc(k)}</div><div class="val">${esc(v)}</div></div>`).join("")}
    </div>
    <h2>Payout Breakup</h2>
    <table>
      <tr><th>Component</th><th>Basis</th><th class="num">Amount</th></tr>
      <tr><td>${esc(base.label)}</td><td>Source value</td><td class="num">${inr(base.amount)}</td></tr>
      <tr><td>Gross Payout</td><td>${pct}% of base</td><td class="num">${inr(gross)}</td></tr>
      <tr><td>TDS @ 5%</td><td>Statutory deduction</td><td class="num">- ${inr(tds)}</td></tr>
      <tr class="totals"><td colspan="2">Net Payout (Receivable)</td><td class="num">${inr(net)}</td></tr>
    </table>
    ${notes ? `<div class="stamp"><b>Notes:</b> ${esc(notes)}</div>` : ""}
    <div class="stamp">Auto-generated by Finance Office · GYC. All figures derived from live system data.</div>
  `;
  openHtmlPrint(html, `Payout - ${reference}`);
}

/* ============== Monthly consolidated statement ============== */

export function buildMonthlyStatement(opts: {
  monthLabel: string;
  module: "insurance" | "loan" | "deal";
  rows: Array<{
    date: string;
    reference: string;
    customer: string;
    productOrType: string;
    base: number;
    pct: number;
    gross: number;
    tds: number;
    net: number;
  }>;
}) {
  const { monthLabel, module, rows } = opts;
  const moduleLabel = module === "insurance" ? "Insurance" : module === "loan" ? "Car Loans" : "Automotive Deals";
  const sum = rows.reduce(
    (a, r) => ({ base: a.base + r.base, gross: a.gross + r.gross, tds: a.tds + r.tds, net: a.net + r.net }),
    { base: 0, gross: 0, tds: 0, net: 0 },
  );
  const html = `
    <h1>${esc(moduleLabel)} Monthly Statement</h1>
    <p class="muted">Period: <b>${esc(monthLabel)}</b> · Records: <b>${rows.length}</b> · Generated ${new Date().toLocaleString("en-IN")}</p>
    <h2>Records</h2>
    <table>
      <tr>
        <th>#</th><th>Date</th><th>Reference</th><th>Customer</th><th>Type</th>
        <th class="num">Base</th><th class="num">%</th><th class="num">Gross</th><th class="num">TDS</th><th class="num">Net</th>
      </tr>
      ${rows.map((r,i) => `
        <tr>
          <td>${i+1}</td>
          <td>${esc(r.date)}</td>
          <td>${esc(r.reference)}</td>
          <td>${esc(r.customer)}</td>
          <td>${esc(r.productOrType)}</td>
          <td class="num">${inr(r.base)}</td>
          <td class="num">${r.pct.toFixed(2)}%</td>
          <td class="num">${inr(r.gross)}</td>
          <td class="num">${inr(r.tds)}</td>
          <td class="num">${inr(r.net)}</td>
        </tr>`).join("")}
      <tr class="totals">
        <td colspan="5">TOTAL</td>
        <td class="num">${inr(sum.base)}</td>
        <td class="num">—</td>
        <td class="num">${inr(sum.gross)}</td>
        <td class="num">${inr(sum.tds)}</td>
        <td class="num">${inr(sum.net)}</td>
      </tr>
    </table>
    <div class="stamp">Auto-generated by Finance Office · GYC. Founder consolidated statement.</div>
  `;
  openHtmlPrint(html, `${moduleLabel}-Statement-${monthLabel}`);
}

/* ============== Full Founder Dashboard Snapshot (PDF) ============== */

export interface FounderSnapshotInput {
  periodLabel: string;
  periodKind: string;
  periodStart: string;
  periodEnd: string;
  filters: { vertical: string; search: string };
  kpis: {
    revenue: number; receivables: number; payroll: number; expenses: number;
    incentives: number; profit: number;
  };
  counts: {
    policies: number; loans: number; loansDisbursed: number;
    deals: number; invoices: number; invoicesPaid: number;
  };
  policies: Array<{ ref: string; customer: string; type: string; base: number; pct: number; gross: number; tds: number; net: number; }>;
  loans: Array<{ ref: string; customer: string; bank: string; stage: string; base: number; pct: number; gross: number; tds: number; net: number; }>;
  deals: Array<{ ref: string; customer: string; vertical: string; value: number; margin: number; pct: number; net: number; received: number; pending: number; }>;
  reconciliation: Array<{ module: string; summaryNet: number; tableNet: number; diff: number; status: string }>;
  audit: Array<{ module: string; query: string; rows: number }>;
}

export function buildFounderSnapshot(s: FounderSnapshotInput) {
  const sum = (arr: number[]) => arr.reduce((a, b) => a + b, 0);
  const polTotals = {
    base: sum(s.policies.map(p => p.base)),
    gross: sum(s.policies.map(p => p.gross)),
    tds: sum(s.policies.map(p => p.tds)),
    net: sum(s.policies.map(p => p.net)),
  };
  const loanTotals = {
    base: sum(s.loans.map(l => l.base)),
    gross: sum(s.loans.map(l => l.gross)),
    tds: sum(s.loans.map(l => l.tds)),
    net: sum(s.loans.map(l => l.net)),
  };
  const dealTotals = {
    value: sum(s.deals.map(d => d.value)),
    margin: sum(s.deals.map(d => d.margin)),
    net: sum(s.deals.map(d => d.net)),
    received: sum(s.deals.map(d => d.received)),
    pending: sum(s.deals.map(d => d.pending)),
  };

  const html = `
    <h1>Founder Master Report — Snapshot</h1>
    <p class="muted">
      Period: <b>${esc(s.periodLabel)}</b> (${esc(s.periodKind)}) · ${esc(s.periodStart)} → ${esc(s.periodEnd)}<br/>
      Filters: vertical=<b>${esc(s.filters.vertical)}</b>${s.filters.search ? ` · search="${esc(s.filters.search)}"` : ""}<br/>
      Generated ${new Date().toLocaleString("en-IN")}
    </p>

    <h2>Headline KPIs</h2>
    <table>
      <tr><th>Metric</th><th class="num">Amount</th><th>Notes</th></tr>
      <tr><td>Revenue (Paid Invoices)</td><td class="num">${inr(s.kpis.revenue)}</td><td>${s.counts.invoicesPaid} paid invoices</td></tr>
      <tr><td>Receivables</td><td class="num">${inr(s.kpis.receivables)}</td><td>${s.counts.invoices - s.counts.invoicesPaid} pending</td></tr>
      <tr><td>Payroll (Net)</td><td class="num">${inr(s.kpis.payroll)}</td><td>—</td></tr>
      <tr><td>Operational Expenses</td><td class="num">${inr(s.kpis.expenses)}</td><td>—</td></tr>
      <tr><td>Total Incentives (Net of TDS)</td><td class="num">${inr(s.kpis.incentives)}</td><td>Insurance + Loans + Deals</td></tr>
      <tr class="totals"><td>Net Profit / Loss</td><td class="num">${s.kpis.profit >= 0 ? "" : "- "}${inr(Math.abs(s.kpis.profit))}</td><td>${s.kpis.profit >= 0 ? "Surplus" : "Deficit"}</td></tr>
    </table>

    <h2>Live Vertical Counts</h2>
    <table>
      <tr><th>Vertical</th><th class="num">Records</th><th>Detail</th></tr>
      <tr><td>Policies Issued</td><td class="num">${s.counts.policies}</td><td>Net Payout: ${inr(polTotals.net)}</td></tr>
      <tr><td>Car Loan Cases</td><td class="num">${s.counts.loans}</td><td>${s.counts.loansDisbursed} disbursed · Net: ${inr(loanTotals.net)}</td></tr>
      <tr><td>Car Sales / Deals</td><td class="num">${s.counts.deals}</td><td>Net Margin: ${inr(dealTotals.net)}</td></tr>
    </table>

    <h2>Reconciliation</h2>
    <table>
      <tr><th>Module</th><th class="num">Summary Net</th><th class="num">Table Net</th><th class="num">Diff</th><th>Status</th></tr>
      ${s.reconciliation.map(r => `
        <tr>
          <td>${esc(r.module)}</td>
          <td class="num">${inr(r.summaryNet)}</td>
          <td class="num">${inr(r.tableNet)}</td>
          <td class="num">${inr(r.diff)}</td>
          <td>${esc(r.status)}</td>
        </tr>`).join("")}
    </table>

    <h2>Audit Trail — Date-range queries</h2>
    <table>
      <tr><th>Module</th><th>Query</th><th class="num">Rows</th></tr>
      ${s.audit.map(a => `<tr><td>${esc(a.module)}</td><td style="font-family:monospace;font-size:10px">${esc(a.query)}</td><td class="num">${a.rows}</td></tr>`).join("")}
    </table>

    <h2>Policies (${s.policies.length})</h2>
    <table>
      <tr><th>#</th><th>Policy</th><th>Customer</th><th>Type</th><th class="num">Base</th><th class="num">%</th><th class="num">Gross</th><th class="num">TDS</th><th class="num">Net</th></tr>
      ${s.policies.map((p,i) => `<tr><td>${i+1}</td><td>${esc(p.ref)}</td><td>${esc(p.customer)}</td><td>${esc(p.type)}</td><td class="num">${inr(p.base)}</td><td class="num">${p.pct}%</td><td class="num">${inr(p.gross)}</td><td class="num">${inr(p.tds)}</td><td class="num">${inr(p.net)}</td></tr>`).join("")}
      <tr class="totals"><td colspan="4">TOTAL</td><td class="num">${inr(polTotals.base)}</td><td class="num">—</td><td class="num">${inr(polTotals.gross)}</td><td class="num">${inr(polTotals.tds)}</td><td class="num">${inr(polTotals.net)}</td></tr>
    </table>

    <h2>Car Loans (${s.loans.length})</h2>
    <table>
      <tr><th>#</th><th>Customer</th><th>Bank</th><th>Stage</th><th class="num">Net Disb.</th><th class="num">%</th><th class="num">Gross</th><th class="num">TDS</th><th class="num">Net</th></tr>
      ${s.loans.map((l,i) => `<tr><td>${i+1}</td><td>${esc(l.customer)}</td><td>${esc(l.bank)}</td><td>${esc(l.stage)}</td><td class="num">${inr(l.base)}</td><td class="num">${l.pct}%</td><td class="num">${inr(l.gross)}</td><td class="num">${inr(l.tds)}</td><td class="num">${inr(l.net)}</td></tr>`).join("")}
      <tr class="totals"><td colspan="4">TOTAL</td><td class="num">${inr(loanTotals.base)}</td><td class="num">—</td><td class="num">${inr(loanTotals.gross)}</td><td class="num">${inr(loanTotals.tds)}</td><td class="num">${inr(loanTotals.net)}</td></tr>
    </table>

    <h2>Car Deals (${s.deals.length})</h2>
    <table>
      <tr><th>#</th><th>Deal</th><th>Customer</th><th>Vertical</th><th class="num">Value</th><th class="num">Margin</th><th class="num">%</th><th class="num">Net</th><th class="num">Received</th><th class="num">Pending</th></tr>
      ${s.deals.map((d,i) => `<tr><td>${i+1}</td><td>${esc(d.ref)}</td><td>${esc(d.customer)}</td><td>${esc(d.vertical)}</td><td class="num">${inr(d.value)}</td><td class="num">${inr(d.margin)}</td><td class="num">${d.pct.toFixed(1)}%</td><td class="num">${inr(d.net)}</td><td class="num">${inr(d.received)}</td><td class="num">${inr(d.pending)}</td></tr>`).join("")}
      <tr class="totals"><td colspan="4">TOTAL</td><td class="num">${inr(dealTotals.value)}</td><td class="num">${inr(dealTotals.margin)}</td><td class="num">—</td><td class="num">${inr(dealTotals.net)}</td><td class="num">${inr(dealTotals.received)}</td><td class="num">${inr(dealTotals.pending)}</td></tr>
    </table>

    <div class="stamp">Founder Master Report Snapshot · GYC Finance Office · Confidential</div>
  `;
  openHtmlPrint(html, `Founder-Snapshot-${s.periodLabel}`);
}

/* ============== CSV Snapshot Export ============== */

export interface ExportColumnConfig {
  policies?: string[];   // subset of: ref,customer,type,base,pct,gross,tds,net
  loans?: string[];      // subset of: ref,customer,bank,stage,base,pct,gross,tds,net
  deals?: string[];      // subset of: ref,customer,vertical,value,margin,pct,net,received,pending
  includeReconciliation?: boolean;
  includeAudit?: boolean;
  includeKpis?: boolean;
  includeCounts?: boolean;
}

const DEFAULT_COLS: Required<Omit<ExportColumnConfig, "includeReconciliation" | "includeAudit" | "includeKpis" | "includeCounts">> = {
  policies: ["ref", "customer", "type", "base", "pct", "gross", "tds", "net"],
  loans: ["ref", "customer", "bank", "stage", "base", "pct", "gross", "tds", "net"],
  deals: ["ref", "customer", "vertical", "value", "margin", "pct", "net", "received", "pending"],
};

const COL_LABELS: Record<string, string> = {
  ref: "Reference", customer: "Customer", type: "Type", bank: "Bank", stage: "Stage",
  vertical: "Vertical", base: "Base", pct: "Pct", gross: "Gross", tds: "TDS", net: "Net",
  value: "Value", margin: "Margin", received: "Received", pending: "Pending",
};

export function buildFounderCSV(s: FounderSnapshotInput, cfg: ExportColumnConfig = {}) {
  const policiesCols = cfg.policies?.length ? cfg.policies : DEFAULT_COLS.policies;
  const loansCols = cfg.loans?.length ? cfg.loans : DEFAULT_COLS.loans;
  const dealsCols = cfg.deals?.length ? cfg.deals : DEFAULT_COLS.deals;
  const includeRecon = cfg.includeReconciliation !== false;
  const includeAudit = cfg.includeAudit !== false;
  const includeKpis = cfg.includeKpis !== false;
  const includeCounts = cfg.includeCounts !== false;

  const esc = (v: any) => {
    const str = String(v ?? "");
    return /[",\n]/.test(str) ? `"${str.replace(/"/g, '""')}"` : str;
  };
  const lines: string[] = [];

  lines.push(`Founder Master Report Snapshot`);
  lines.push(`Period,${esc(s.periodLabel)},${esc(s.periodKind)},${s.periodStart},${s.periodEnd}`);
  lines.push(`Filters,vertical=${esc(s.filters.vertical)},search=${esc(s.filters.search)}`);
  lines.push(`Generated,${new Date().toISOString()}`);
  lines.push("");

  if (includeKpis) {
    lines.push("== KPIs ==");
    lines.push("Metric,Amount");
    lines.push(`Revenue (Paid),${s.kpis.revenue}`);
    lines.push(`Receivables,${s.kpis.receivables}`);
    lines.push(`Payroll,${s.kpis.payroll}`);
    lines.push(`Expenses,${s.kpis.expenses}`);
    lines.push(`Incentives Net,${s.kpis.incentives}`);
    lines.push(`Net Profit/Loss,${s.kpis.profit}`);
    lines.push("");
  }

  if (includeCounts) {
    lines.push("== Counts ==");
    lines.push(`Policies,${s.counts.policies}`);
    lines.push(`Loans Total,${s.counts.loans}`);
    lines.push(`Loans Disbursed,${s.counts.loansDisbursed}`);
    lines.push(`Deals,${s.counts.deals}`);
    lines.push(`Invoices Total,${s.counts.invoices}`);
    lines.push(`Invoices Paid,${s.counts.invoicesPaid}`);
    lines.push("");
  }

  if (includeRecon) {
    lines.push("== Reconciliation ==");
    lines.push("Module,Summary Net,Table Net,Diff,Status");
    s.reconciliation.forEach(r => lines.push(`${esc(r.module)},${r.summaryNet},${r.tableNet},${r.diff},${esc(r.status)}`));
    lines.push("");
  }

  if (includeAudit) {
    lines.push("== Audit Trail ==");
    lines.push("Module,Query,Rows");
    s.audit.forEach(a => lines.push(`${esc(a.module)},${esc(a.query)},${a.rows}`));
    lines.push("");
  }

  if (policiesCols.length) {
    lines.push(`== Policies (${s.policies.length}) ==`);
    lines.push(policiesCols.map(c => COL_LABELS[c] || c).join(","));
    s.policies.forEach(p => lines.push(policiesCols.map(c => esc((p as any)[c])).join(",")));
    lines.push("");
  }

  if (loansCols.length) {
    lines.push(`== Loans (${s.loans.length}) ==`);
    lines.push(loansCols.map(c => COL_LABELS[c] || c).join(","));
    s.loans.forEach(l => lines.push(loansCols.map(c => esc((l as any)[c])).join(",")));
    lines.push("");
  }

  if (dealsCols.length) {
    lines.push(`== Deals (${s.deals.length}) ==`);
    lines.push(dealsCols.map(c => COL_LABELS[c] || c).join(","));
    s.deals.forEach(d => lines.push(dealsCols.map(c => esc((d as any)[c])).join(",")));
  }

  const csv = lines.join("\n");
  return csv;
}

export function downloadFounderCSV(s: FounderSnapshotInput, cfg: ExportColumnConfig = {}) {
  const csv = buildFounderCSV(s, cfg);
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `Founder-Snapshot-${s.periodLabel.replace(/\s+/g, "_")}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/* ============== Founder Snapshot HTML (for PDF/Email body) ============== */

export function buildFounderSnapshotHTML(s: FounderSnapshotInput, cfg: ExportColumnConfig = {}): string {
  const policiesCols = cfg.policies?.length ? cfg.policies : DEFAULT_COLS.policies;
  const loansCols = cfg.loans?.length ? cfg.loans : DEFAULT_COLS.loans;
  const dealsCols = cfg.deals?.length ? cfg.deals : DEFAULT_COLS.deals;
  const includeRecon = cfg.includeReconciliation !== false;
  const includeAudit = cfg.includeAudit !== false;

  const sum = (arr: number[]) => arr.reduce((a, b) => a + b, 0);
  const polTotals = {
    base: sum(s.policies.map(p => p.base)), gross: sum(s.policies.map(p => p.gross)),
    tds: sum(s.policies.map(p => p.tds)), net: sum(s.policies.map(p => p.net)),
  };
  const loanTotals = {
    base: sum(s.loans.map(l => l.base)), gross: sum(s.loans.map(l => l.gross)),
    tds: sum(s.loans.map(l => l.tds)), net: sum(s.loans.map(l => l.net)),
  };
  const dealTotals = {
    value: sum(s.deals.map(d => d.value)), margin: sum(s.deals.map(d => d.margin)),
    net: sum(s.deals.map(d => d.net)), received: sum(s.deals.map(d => d.received)),
    pending: sum(s.deals.map(d => d.pending)),
  };

  const renderTable = (cols: string[], rows: any[], totals?: Record<string, number>) => `
    <table>
      <tr>${cols.map(c => `<th class="${["base","pct","gross","tds","net","value","margin","received","pending"].includes(c) ? "num" : ""}">${esc(COL_LABELS[c] || c)}</th>`).join("")}</tr>
      ${rows.map(r => `<tr>${cols.map(c => {
        const v = r[c];
        const isNum = typeof v === "number";
        return `<td class="${isNum ? "num" : ""}">${isNum ? (c === "pct" ? `${v}%` : inr(v)) : esc(v)}</td>`;
      }).join("")}</tr>`).join("")}
      ${totals ? `<tr class="totals">${cols.map(c => {
        if (totals[c] !== undefined) return `<td class="num">${inr(totals[c])}</td>`;
        return `<td>${c === cols[0] ? "TOTAL" : "—"}</td>`;
      }).join("")}</tr>` : ""}
    </table>`;

  return `
    <h1>Founder Master Report — Snapshot</h1>
    <p class="muted">
      Period: <b>${esc(s.periodLabel)}</b> (${esc(s.periodKind)}) · ${esc(s.periodStart)} → ${esc(s.periodEnd)}<br/>
      Filters: vertical=<b>${esc(s.filters.vertical)}</b>${s.filters.search ? ` · search="${esc(s.filters.search)}"` : ""}<br/>
      Generated ${new Date().toLocaleString("en-IN")}
    </p>

    <h2>Headline KPIs</h2>
    <table>
      <tr><th>Metric</th><th class="num">Amount</th></tr>
      <tr><td>Revenue (Paid)</td><td class="num">${inr(s.kpis.revenue)}</td></tr>
      <tr><td>Receivables</td><td class="num">${inr(s.kpis.receivables)}</td></tr>
      <tr><td>Payroll (Net)</td><td class="num">${inr(s.kpis.payroll)}</td></tr>
      <tr><td>Operational Expenses</td><td class="num">${inr(s.kpis.expenses)}</td></tr>
      <tr><td>Total Incentives</td><td class="num">${inr(s.kpis.incentives)}</td></tr>
      <tr class="totals"><td>Net Profit / Loss</td><td class="num">${s.kpis.profit >= 0 ? "" : "- "}${inr(Math.abs(s.kpis.profit))}</td></tr>
    </table>

    ${includeRecon ? `
    <h2>Auto-Reconciliation</h2>
    <table>
      <tr><th>Module</th><th class="num">Summary Net</th><th class="num">Table Net</th><th class="num">Diff</th><th>Status</th></tr>
      ${s.reconciliation.map(r => `<tr><td>${esc(r.module)}</td><td class="num">${inr(r.summaryNet)}</td><td class="num">${inr(r.tableNet)}</td><td class="num">${inr(r.diff)}</td><td>${esc(r.status)}</td></tr>`).join("")}
    </table>` : ""}

    ${includeAudit ? `
    <h2>Audit Trail — Date-range queries</h2>
    <table>
      <tr><th>Module</th><th>Query</th><th class="num">Rows</th></tr>
      ${s.audit.map(a => `<tr><td>${esc(a.module)}</td><td style="font-family:monospace;font-size:10px">${esc(a.query)}</td><td class="num">${a.rows}</td></tr>`).join("")}
    </table>` : ""}

    ${policiesCols.length ? `<h2>Policies (${s.policies.length})</h2>${renderTable(policiesCols, s.policies, polTotals as any)}` : ""}
    ${loansCols.length ? `<h2>Car Loans (${s.loans.length})</h2>${renderTable(loansCols, s.loans, loanTotals as any)}` : ""}
    ${dealsCols.length ? `<h2>Car Deals (${s.deals.length})</h2>${renderTable(dealsCols, s.deals, dealTotals as any)}` : ""}

    <div class="stamp">Founder Master Report Snapshot · GYC Finance Office · Confidential</div>
  `;
}

export function buildFounderSnapshotWithConfig(s: FounderSnapshotInput, cfg: ExportColumnConfig = {}) {
  const html = buildFounderSnapshotHTML(s, cfg);
  openHtmlPrint(html, `Founder-Snapshot-${s.periodLabel}`);
}

export function getFounderSnapshotPrintableHTML(s: FounderSnapshotInput, cfg: ExportColumnConfig = {}): string {
  const body = buildFounderSnapshotHTML(s, cfg);
  return `<!doctype html><html><head><meta charset="utf-8"/><title>Founder Snapshot</title><style>${css}</style></head><body>${body}</body></html>`;
}
